{-# LANGUAGE ScopedTypeVariables #-}
module Main where
import Bridge.Types
import Bridge.Process (runBoundedWithEnvironment)
import Bridge.Config
import qualified Bridge.Postgres.Maintenance as Maintenance
import Bridge.Ledger.Model
import Bridge.SolanaMessage
import qualified Bridge.SolanaPay as Pay
import Bridge.SolanaDeposit
import Bridge.Solana (inspectTokenAccount)
import Bridge.SDKBuild (sdkLibraryPath, sdkSourceDirectory, sdkTargetDirectory)
import qualified Data.Map.Strict as M
import Bridge.SolanaHelper
import Bridge.SolanaPayment
import qualified Data.Aeson.KeyMap as KM
import qualified Data.Aeson.Key as Key
import Bridge.Native (nativeAmount,nativeNumber,validateNativeRecipientWith,nativeWalletInfoWith,nativeWalletReadyWith)
import Bridge.NativePayment
import Bridge.NativeReplacement
import Bridge.Settlement
import Bridge.Admission
import Bridge.RPC
import Bridge.API (CustomerAPI, customerAPI)
import qualified Bridge.API as API
import Bridge.Control (runControl, callControl)
import Bridge.Operator (signingApplication,signingAPI,signerCredentials,signerCertificate)
import qualified Bridge.Postgres.Runtime as Runtime
import Bridge.Web (runUnix,publicApplication,securityBoundary)
import qualified Database.PostgreSQL.Simple as PG
import Servant (BasicAuthData(..),serve,throwError,err409,Handler,Server)
import Network.Wai (defaultRequest,responseLBS,requestMethod,requestHeaders)
import Network.Wai.Handler.Warp (testWithApplication,openFreePort,setBeforeMainLoop,defaultSettings)
import Network.Wai.Handler.WarpTLS (runTLSSocket,tlsSettings)
import qualified Network.Socket as NS
import Network.HTTP.Client (closeManager,newManager)
import Network.HTTP.Client.TLS (mkManagerSettings)
import qualified Network.Connection as NC
import qualified Network.TLS as TLS
import Network.TLS.Extra.Cipher (ciphersuite_default)
import Data.Default (def)
import Data.PEM (pemParseBS,pemContent)
import Data.X509 (decodeSignedCertificate,CertificateChain(..))
import Data.X509.Validation (validateDefault,FailedReason(..))
import Data.X509.CertificateStore (makeCertificateStore)
import Control.Concurrent.MVar (newEmptyMVar,putMVar,takeMVar)
import Network.HTTP.Types (status200,status404,status403,status409,status400,status413,status401)
import qualified Network.Wai.Test as W
import Bridge.Observer
import Control.Concurrent (threadDelay)
import Control.Concurrent.Async (withAsync,concurrently_,link)
import Control.Exception (bracket,SomeException,try)
import Control.Monad (forM_,when,void)
import Data.Aeson
import Data.Aeson.Types (parseEither)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as LBS
import qualified Data.ByteString.Base64 as B64
import Data.Int (Int64)
import Data.IORef
import Data.List (elemIndex)
import Crypto.Error (CryptoFailable(..))
import qualified Crypto.PubKey.Ed25519 as Ed
import qualified Data.ByteArray as BA
import Data.String (fromString)
import Data.Scientific (scientific)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Servant.API ((:<|>)(..))
import Servant.Client
import System.Directory
import System.FilePath ((</>))
import System.Posix.Files (getFileStatus,fileMode,setFileMode)
import Data.Bits ((.&.),xor)
import Data.Word (Word8)
import System.Exit (ExitCode(..))
import System.Environment (lookupEnv,getEnvironment)
import System.Process (readProcessWithExitCode)
import System.Timeout (timeout)
import Test.Hspec hiding (before,after)
import Test.QuickCheck hiding ((.&.))

-- Transport-only fixture: exercises real Servant routing, Unix permissions and
-- reconnects, with no ledger, chain model, wallet or financial implementation.
customerFixture :: Server CustomerAPI
customerFixture =
  let unavailable :: Handler a
      unavailable = throwError err409
      c=cfg "/fixture"
      public=API.PublicConfiguration (profile c) "devnet" (defaultInterface $ profile c)
        (deploymentId c) (mint c) (custodyOwner c) 8 (minInput c) (maxInput c)
        (M.fromList [("NativeToWrapped",100),("WrappedToNative",100)]) False False
        (Availability False "observation_only")
  in pure public :<|> (\_ _ -> unavailable) :<|> (\_ _ -> unavailable)
       :<|> (\_ _ -> unavailable)

socketFixture :: Config -> IO ()
socketFixture c = do
  customerApp <- securityBoundary (serve customerAPI customerFixture)
  concurrently_ (runUnix (customerSocket c) 0o660 customerApp)
                (runControl c (\_ -> reject "fixture_operation_unavailable"))

-- Exercise the release command itself on generated bytes. No installer is run.
data ReleaseFault = OriginalRelease | ChangedIndex | ChangedSignature | ChangedArtifact
  | WrongTrustKey | PublicSigningKey | UnexpectedInstallArguments
  deriving (Eq,Show,Enum,Bounded)

releaseAuthentication :: ReleaseFault -> [Word8] -> String -> IO Bool
releaseAuthentication fault seed arch = withDir $ \dir->do
  let key=dir</>"key.pem"
      public=dir</>"public.pem"
      index=dir</>"release-index.json"
      signature=dir</>"release-index.sig"
      bytes=BS.pack seed
      privatePrefix=BS.pack [0x30,0x2e,0x02,0x01,0x00,0x30,0x05,0x06,0x03,0x2b,0x65,0x70,0x04,0x22,0x04,0x20]
      publicPrefix=BS.pack [0x30,0x2a,0x30,0x05,0x06,0x03,0x2b,0x65,0x70,0x03,0x21,0x00]
      pem tag content="-----BEGIN "<>tag<>"-----\n"<>B64.encode content<>"\n-----END "<>tag<>"-----\n"
      publicBytes inputBytes=case Ed.secretKey inputBytes of
        CryptoPassed secret->BA.convert (Ed.toPublic secret)
        CryptoFailed _->error "generated seed must have 32 bytes"
      call args=do
        (code,_,_) <- readProcessWithExitCode "scripts/release-auth" args ""
        pure code
  BS.writeFile key (pem "PRIVATE KEY" (privatePrefix<>bytes))
  setFileMode key (if fault==PublicSigningKey then 0o644 else 0o600)
  BS.writeFile public (pem "PUBLIC KEY" (publicPrefix<>publicBytes bytes))
  forM_ ["aarch64","x86_64"] $ \cpu->do
    let name="ecx-bridge-ubuntu-24.04-"<>cpu<>".run"
    BS.writeFile (dir</>name) bytes
    writeFile (dir</>(name<>".sha256")) (T.unpack (digest bytes)<>"  "<>name<>"\n")
  signed <- call ["sign",key,dir]
  if fault==PublicSigningKey then do
    indexExists <- doesPathExist index
    signatureExists <- doesPathExist signature
    pure (signed/=ExitSuccess && not indexExists && not signatureExists)
  else do
    require (signed==ExitSuccess) "release_fixture_signing_failed"
    case fault of
      ChangedIndex->BS.appendFile index " "
      ChangedSignature->BS.readFile signature >>= \original->BS.writeFile signature
        (BS.cons (BS.head original `xor` 1) (BS.tail original))
      ChangedArtifact->BS.appendFile (dir</>("ecx-bridge-ubuntu-24.04-"<>arch<>".run")) "changed"
      WrongTrustKey->BS.writeFile public (pem "PUBLIC KEY" (publicPrefix<>
        publicBytes (BS.cons (BS.head bytes `xor` 1) (BS.tail bytes))))
      _->pure ()
    verified <- call (["verify",public,dir,arch]<>
      if fault==UnexpectedInstallArguments then ["--","--test-worker"] else [])
    pure ((verified==ExitSuccess)==(fault==OriginalRelease))


amt :: Integer -> Amount
amt n = either (error . T.unpack) id (amount n)
cfg :: FilePath -> Config
cfg dir = Config L2LSignetDevnet "unit-fixture" "http://127.0.0.1:29432" (dir</>"cookie") "fixture-wallet" 16000 "00000047dcc9d64b767687d6a5e610c411dd85db5460e824c0f7284f5514bc47" "https://api.devnet.solana.com" Nothing "Hqb82J658UeWXCdr6DA6Au2ChMzrhxoSd3vdXk2hkNqM" "RWjpjjkpABkEGomLbZYyN53pA3FVdPXp9izJ25wErGX" "11111111111111111111111111111111" (dir</>"customer/api.sock") (dir</>"admin/api.sock") 8081 (dir</>"signing.auth") (dir</>"sdk-library") (amt 2) (amt 1000000000000) 100 300 600 1 (amt 1000) (amt 10000) False Nothing (amt 0) Nothing (amt 100000) (amt 100000000)
req :: OrderRequest
req=OrderRequest NativeToWrapped (amt 100000) "fixture-solana-recipient" "fixture-native-refund" Nothing "retry-key"
withDir :: (FilePath -> IO a) -> IO a
withDir action=do
  base <- getTemporaryDirectory
  ident <- T.take 12 <$> randomId
  bracket (let p=base</>("ecx-test-"<>T.unpack ident) in createDirectory p >> pure p) removePathForcibly action
-- Real temporary certificate chain; no network, wallet or fixed expiry fixture.
constrainedIssuer :: FilePath -> IO (String -> IO [FailedReason])
constrainedIssuer dir = do
  setFileMode dir 0o700
  environment <- getEnvironment
  let file name=dir</>name
      openssl args=void $ runBoundedWithEnvironment environment 30 8192 "openssl" args BS.empty
      key name=openssl ["genpkey","-algorithm","EC","-pkeyopt","ec_paramgen_curve:prime256v1","-out",file (name<>".key")]
      csr name subject=openssl ["req","-new","-key",file (name<>".key"),"-out",file (name<>".csr"),"-subj","/CN="<>subject]
      sign name issuer=openssl ["x509","-req","-in",file (name<>".csr"),"-CA",file (issuer<>".pem"),"-CAkey",file (issuer<>".key")
        ,"-CAcreateserial","-out",file (name<>".pem"),"-days","1","-extfile",file (name<>".ext")]
      certificate name=do
        bytes <- BS.readFile (file $ name<>".pem")
        pems <- either fail pure (pemParseBS bytes)
        case pems of [pem]->either fail pure (decodeSignedCertificate $ pemContent pem); _->fail "one fixture certificate required"
  key "root"
  openssl ["req","-x509","-new","-key",file "root.key","-out",file "root.pem","-days","1","-subj","/CN=Temporary fixture root"
    ,"-addext","basicConstraints=critical,CA:TRUE","-addext","keyUsage=critical,keyCertSign,cRLSign"]
  key "issuer"
  csr "issuer" "Temporary constrained issuer"
  writeFile (file "issuer.ext") "basicConstraints=critical,CA:TRUE\nkeyUsage=critical,keyCertSign,cRLSign\nnameConstraints=critical,permitted;DNS:allowed.example,excluded;DNS:blocked.allowed.example\n"
  sign "issuer" "root"
  root <- certificate "root"
  issuer <- certificate "issuer"
  key "leaf"
  pure $ \name->do
    csr "leaf" name
    writeFile (file "leaf.ext") ("basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nsubjectAltName=DNS:"<>name<>"\n")
    sign "leaf" "issuer"
    leaf <- certificate "leaf"
    validateDefault (makeCertificateStore [root]) def (name,BS.empty) (CertificateChain [leaf,issuer])

isError :: Text -> BridgeError -> Bool
isError expected (BridgeError actual)=expected==actual
nativeFixture :: IO (NativePlan,[NativePrevout],Amount,NativeTx)
nativeFixture = do
  value <- BS.readFile "test/fixtures/native-signet-payment.json" >>= either fail pure . eitherDecodeStrict'
  plan <- fieldValue "plan" value
  previous <- fieldValue "previous" value
  fee <- fieldValue "fee" value
  decoded <- fieldValue "decoded" value >>= either (fail . T.unpack) pure . decodeNativeTx
  pure (plan,previous,fee,decoded)

nativeSignedFixture :: IO NativeSigned
nativeSignedFixture=do
  value<-BS.readFile "test/fixtures/native-signet-payment.json" >>= either fail pure . eitherDecodeStrict'
  (plan,previous,fee,tx)<-nativeFixture
  raw<-fieldValue "raw" value
  pure (NativeSigned raw tx plan previous fee)

-- A real unsigned PSBT/decoded template, with modeled pending wallet state.
-- The captured input payment is actually confirmed; these are offline RPC
-- contracts, never evidence that a replacement was broadcast on Signet.
withNativeReplacementContract :: (Config -> NativeSigned -> NativeDraft -> NativeRPC -> IORef [(Text,[Value])] -> IO a) -> IO a
withNativeReplacementContract action=do
  original<-nativeSignedFixture
  captured<-BS.readFile "test/fixtures/native-signet-payment.json" >>= either fail pure . eitherDecodeStrict'
  replacement<-BS.readFile "test/fixtures/native-signet-replacement-draft.json" >>= either fail pure . eitherDecodeStrict'
  oldDecoded<-fieldValue "decoded" captured :: IO Value
  newDecoded<-fieldValue "decoded" replacement :: IO Value
  draft<-fieldValue "draft" replacement
  created<-fieldValue "createdPsbt" replacement :: IO Text
  calls<-newIORef []
  let c=cfg "offline-native-replacement"
      plan=signedNativePlan original
      tx=signedNativeTransaction original
      position=object ["hash" .= custodyNativeTip,"height" .= (16010::Int)]
      call _ method params=do
        modifyIORef' calls (<>[(method,params)])
        case (method,params) of
          ("getblockchaininfo",[])->pure $ object ["chain" .= ("signet"::Text),"initialblockdownload" .= False
            ,"blocks" .= (16010::Int),"bestblockhash" .= custodyNativeTip,"signet_challenge" .= signetChallenge]
          ("getblockhash",[height]) | height==toJSON (nativeCheckpointHeight c)->pure $ toJSON $ nativeCheckpointHash c
          ("getblockhash",[Number 16010])->pure $ toJSON custodyNativeTip
          ("getconnectioncount",[])->pure $ toJSON (1::Int)
          ("getwalletinfo",[])->pure $ object ["walletname" .= nativeWallet c,"descriptors" .= True,"private_keys_enabled" .= True
            ,"external_signer" .= False,"scanning" .= False,"lastprocessedblock" .= position]
          ("decoderawtransaction",[raw]) | raw==toJSON (signedNativeBytes original)->pure oldDecoded
          ("getaddressinfo",[address]) | address==toJSON (planRecipient plan)->pure $ object ["ismine" .= False,"scriptPubKey" .= planRecipientScript plan]
          ("getaddressinfo",[address]) | address==toJSON (planChange plan)->pure $ object ["ismine" .= True,"scriptPubKey" .= planChangeScript plan]
          ("decodescript",[_])->pure $ object ["type" .= ("witness_v0_keyhash"::Text)]
          ("gettransaction",[txid,Bool False,Bool True]) | txid==toJSON (nativeTxid tx)->pure $ object
            ["txid" .= nativeTxid tx,"hex" .= signedNativeBytes original,"decoded" .= oldDecoded
            ,"fee" .= scientific (negate $ toInteger $ units $ signedNativeFee original) (-8),"confirmations" .= (0::Int)
            ,"walletconflicts" .= ([]::[Text]),"lastprocessedblock" .= position]
          ("gettxout",[txid,index,Bool False])->case [p | p<-signedNativePrevouts original
              ,txid==toJSON (outpointTxid $ prevout p),index==toJSON (outpointVout $ prevout p)] of
            [p]->pure $ object ["bestblock" .= custodyNativeTip,"value" .= nativeNumber (prevoutAmount p)
              ,"confirmations" .= prevoutDepth p,"coinbase" .= prevoutCoinbase p
              ,"scriptPubKey" .= object ["hex" .= prevoutScript p,"address" .= ("offline-prevout-address"::Text)]]
            _->reject "unexpected_replacement_prevout"
          ("getaddressinfo",[String "offline-prevout-address"])->case signedNativePrevouts original of
            [p]->pure $ object ["ismine" .= True,"scriptPubKey" .= prevoutScript p]
            _->reject "unexpected_fixture_prevouts"
          ("gettxspendingprevout",[points])->do
            points `shouldBe` toJSON (map nativeOutpoint $ nativeInputs tx)
            pure $ toJSON [object ["txid" .= outpointTxid point,"vout" .= outpointVout point,"spendingtxid" .= nativeTxid tx]
              | point<-map nativeOutpoint $ nativeInputs tx]
          ("listlockunspent",[])->pure $ toJSON $ map nativeOutpoint $ nativeInputs tx
          ("createpsbt",[inputs,outputs,locktime,Bool False])->do
            inputs `shouldBe` toJSON [object ["txid" .= outpointTxid point,"vout" .= outpointVout point,"sequence" .= nativeSequence input]
              | input<-nativeInputs tx,let point=nativeOutpoint input]
            locktime `shouldBe` toJSON (nativeLocktime tx)
            outputs `shouldBe` toJSON [object [Key.fromText (if nativeOutputScript o==planRecipientScript plan then planRecipient plan else planChange plan)
              .= nativeNumber (nativeOutputAmount o)] | o<-nativeOutputs $ draftTransaction draft]
            pure $ toJSON created
          ("walletprocesspsbt",[psbt,Bool False,String "ALL",Bool False,Bool False])->do
            psbt `shouldBe` toJSON created
            pure $ object ["psbt" .= draftPsbt draft,"complete" .= False]
          ("decodepsbt",[psbt]) | psbt==toJSON (draftPsbt draft)->pure newDecoded
          _->reject $ "unexpected_replacement_rpc:"<>method
  action c original draft call calls

withNativeAdmission :: (Config -> NativePlan -> IORef [Text] -> NativeRPC -> IO a) -> IO a
withNativeAdmission action=do
  (plan,previous,fee,_)<-nativeFixture
  captured<-BS.readFile "test/fixtures/native-signet-payment.json" >>= either fail pure . eitherDecodeStrict'
  decoded<-fieldValue "decoded" captured :: IO Value
  prev<-case previous of [p]->pure p; _->fail "expected one captured previous output"
  calls<-newIORef []
  let c=cfg "/unused-native-admission-fixture"
      call wallet method params=do
        modifyIORef' calls (<>[method])
        case (method,params) of
          ("getaddressinfo",[String address]) -> do
            wallet `shouldBe` True
            pure $ object ["ismine" .= (address/=planRecipient plan),"scriptPubKey" .=
              (if address==planRecipient plan then planRecipientScript plan
                else if address==planChange plan then planChangeScript plan else prevoutScript prev)]
          ("decodescript",[String script]) -> do
            wallet `shouldBe` False
            script `shouldBe` planRecipientScript plan
            pure $ object ["type" .= ("witness_v0_keyhash"::Text)]
          ("listunspent",[depth,_,_,unsafe,options]) -> do
            wallet `shouldBe` True
            depth `shouldBe` toJSON (nativeConfirmations c)
            unsafe `shouldBe` Bool False
            fieldValue "maximumCount" options `shouldReturn` (100::Int)
            pure $ toJSON [object ["address" .= planChange plan,"confirmations" .= (1000::Int),"safe" .= True,"spendable" .= True,"solvable" .= True]]
          ("listlockunspent",_) -> pure $ toJSON ([]::[Outpoint])
          ("walletcreatefundedpsbt",[_,outputs,locktime,options,_]) -> do
            fieldValue "lockUnspents" options `shouldReturn` False
            fieldValue "replaceable" options `shouldReturn` False
            fieldValue "include_unsafe" options `shouldReturn` False
            fieldValue "changeAddress" options `shouldReturn` planChange plan
            fieldValue "minconf" options `shouldReturn` nativeConfirmations c
            locktime `shouldBe` toJSON (0::Int)
            outputs `shouldBe` toJSON [object [fromString (T.unpack $ planRecipient plan) .= nativeNumber (planAmount plan)]]
            pure $ object ["psbt" .= ("unsigned-admission-fixture"::Text),"fee" .= nativeNumber fee,"changepos" .= (0::Int)]
          ("decodepsbt",_) -> pure $ object ["tx" .= decoded,"fee" .= nativeNumber fee]
          ("gettxout",_) -> pure $ object ["value" .= nativeNumber (prevoutAmount prev),"confirmations" .= (1000::Int),"coinbase" .= False
            ,"scriptPubKey" .= object ["hex" .= prevoutScript prev,"address" .= ("fixture-prevout"::Text)]]
          _ -> expectationFailure ("unexpected native admission RPC: "<>T.unpack method) >> pure Null
  action c plan calls call

fixture :: FilePath -> IO (Expected,Text)
fixture name=do
  bytes<-BS.readFile ("test/fixtures"</>name)
  value<-either fail pure (eitherDecodeStrict' bytes)
  either fail pure $ parseEither (withObject "fixture" $ \o->do
    r<-o .: "reply"
    expected<-Expected <$> o .: "owner" <*> o .: "recipient" <*> o .: "mint" <*> r .: "source_ata" <*> r .: "destination_ata" <*> o .: "blockhash" <*> o .: "amount" <*> r .: "memo" <*> o .: "createAta" <*> o .: "signed"
    encoded<-r .: "transaction"
    pure (expected,encoded)) value

awaitFile :: FilePath -> Int -> IO ()
awaitFile _ 0 = fail "socket startup timed out"
awaitFile path tries = do
  present<-doesPathExist path
  if present then pure () else threadDelay 10000 >> awaitFile path (tries-1)

-- Re-index the contract fixture using the documented v0 loaded-address layout.
-- This tests decoding only; it is not a signed or submitted chain transaction.
versionZeroFixture :: Text -> Value -> IO Value
versionZeroFixture custody proof = do
  root<-parseValue (withObject "proof" pure) proof
  transaction<-fieldValue "transaction" proof
  tx<-parseValue (withObject "transaction" pure) transaction
  message<-fieldValue "message" transaction
  msg<-parseValue (withObject "message" pure) message
  keys<-fieldValue "accountKeys" message :: IO [Text]
  metaValue<-fieldValue "meta" proof
  meta<-parseValue (withObject "meta" pure) metaValue
  idx<-case [i | (i,k)<-zip [0..] keys,k==custody] of [i]->pure i; _->fail "missing custody"
  let static=[i | i<-[0..length keys-1],i/=idx]
      order=static<>[idx]
      remap old=case lookup old (zip order [0..]) of Just new->new::Int; Nothing->error "fixture index"
  instructions<-fieldValue "instructions" message :: IO [Value]
  rewritten<-mapM (\v -> do
    p<-fieldValue "programIdIndex" v
    accounts<-fieldValue "accounts" v
    dat<-fieldValue "data" v :: IO Text
    pure $ object ["programIdIndex" .= remap p,"accounts" .= map remap accounts,"data" .= dat]) instructions
  let changeBalances key=do
        rows<-fieldValue key metaValue :: IO [Value]
        mapM (\v -> do
          fields<-parseValue (withObject "balance" pure) v
          i<-fieldValue "accountIndex" v
          pure $ Object (KM.insert "accountIndex" (toJSON $ remap i) fields)) rows
  before<-changeBalances "preTokenBalances"
  after<-changeBalances "postTokenBalances"
  preLamports<-fieldValue "preBalances" metaValue :: IO [Int64]
  postLamports<-fieldValue "postBalances" metaValue :: IO [Int64]
  let newMsg=Object $ KM.insert "accountKeys" (toJSON $ map (keys!!) static) $ KM.insert "instructions" (toJSON rewritten) msg
      newMeta=Object $ KM.insert "loadedAddresses" (object ["writable" .= [custody],"readonly" .= ([]::[Text])])
        $ KM.insert "preTokenBalances" (toJSON before) $ KM.insert "postTokenBalances" (toJSON after)
        $ KM.insert "preBalances" (toJSON $ map (preLamports!!) order) $ KM.insert "postBalances" (toJSON $ map (postLamports!!) order) meta
  pure $ Object $ KM.insert "version" (Number 0) $ KM.insert "meta" newMeta
    $ KM.insert "transaction" (Object $ KM.insert "message" newMsg tx) root

-- Contract fixture generated from official SDK message bytes, not chain evidence.
-- No current getAccountInfo is available or needed: ownership comes from metadata.
depositFixture :: IO (DepositBinding,Value)
depositFixture=do
  (expected,encoded)<-fixture "unsigned-three-units.json"
  tx<-either (fail . T.unpack) pure (decodeTransaction encoded)
  case tx of
    Transaction _ (Message required signedReadonly unsignedReadonly keys blockhash instructions) _ -> do
      let keyAt i=base58 (keys!!i)
          tokenBalance i n=object ["accountIndex" .= i,"mint" .= expectedMint expected,"owner" .= (if keyAt i==expectedSource expected then expectedOwner expected else expectedRecipient expected),"uiTokenAmount" .= object ["amount" .= (n::Text),"decimals" .= (8::Int)]]
          indexOf key=case [i | (i,k)<-zip [0..] keys,base58 k==key] of [i]->i; _->error "missing fixture account"
          sourceIndex=indexOf (expectedSource expected)
          destIndex=indexOf (expectedDestination expected)
          sig="fixture-signature"
          proof=object ["slot" .= (123::Int),"version" .= ("legacy"::Text)
            ,"transaction" .= object ["signatures" .= [sig],"message" .= object ["accountKeys" .= map base58 keys,"recentBlockhash" .= base58 blockhash,"header" .= object ["numRequiredSignatures" .= required,"numReadonlySignedAccounts" .= signedReadonly,"numReadonlyUnsignedAccounts" .= unsignedReadonly],"instructions" .= [object ["programIdIndex" .= p,"accounts" .= as,"data" .= base58 dat] | Instruction p as dat<-instructions]]]
            ,"meta" .= object ["err" .= Null,"preTokenBalances" .= [tokenBalance sourceIndex "10",tokenBalance destIndex "0"],"postTokenBalances" .= [tokenBalance sourceIndex "7",tokenBalance destIndex "3"],"preBalances" .= replicate (length keys) (2039280::Int64),"postBalances" .= replicate (length keys) (2039280::Int64),"innerInstructions" .= ([]::[Value])]]
          binding=DepositBinding sig (expectedOwner expected) (expectedMint expected) (expectedDestination expected) (expectedRecipient expected) (expectedMemo expected)
      pure(binding,proof)

-- Transport-only fixtures: no validator, network, or acceptance result is faked.
solanaFixture :: IO (Config,SolanaPlan,HelperReply)
solanaFixture=do
  value<-BS.readFile "test/fixtures/signed-three-units.json" >>= either fail pure . eitherDecodeStrict'
  reply<-fieldValue "reply" value
  owner<-fieldValue "owner" value
  target<-fieldValue "recipient" value
  token<-fieldValue "mint" value
  hash<-fieldValue "blockhash" value
  let c=(cfg "/unused-codec-test"){deploymentId="codec-fixture",mint=token,custodyOwner=owner,custodyAta=replySource reply,maxSolFee=amt 10000,maxSolAccountRent=amt 2100000}
      plan=SolanaPlan (fingerprint c) target (amt 3) "order-1" (RecentBlockhash hash 1000 100) (maxSolFee c) (maxSolAccountRent c)
  pure(c,plan,reply)

contextContract :: Value -> Value
contextContract value=object ["context" .= object ["slot" .= (100::Int)],"value" .= value]

custodyNativeTip :: Text
custodyNativeTip=T.replicate 64 "d"

-- These explicit RPC fixtures are unit contracts, not substitute networks.
withSolanaAdmission :: (Config -> OrderRequest -> SolanaRPC -> (HelperRequest -> IO HelperReply) -> IO a) -> IO a
withSolanaAdmission action=do
  value<-BS.readFile "test/fixtures/admission-unsigned.json" >>= either fail pure . eitherDecodeStrict'
  deployment<-fieldValue "deploymentId" value
  token<-fieldValue "mint" value
  custody<-fieldValue "custodyOwner" value
  wallet<-fieldValue "wallet" value
  hash<-fieldValue "blockhash" value
  payout<-fieldValue "payout" value
  let c=(cfg "/unused-admission-test"){deploymentId=deployment,mint=token,custodyOwner=custody,custodyAta=replySource payout
        ,maxSolAccountRent=amt 2100000}
      request=OrderRequest NativeToWrapped (amt 4) wallet "fixture-native-refund" Nothing "fixture-admission"
      helper r=do
        helperAmount r `shouldBe` amt 3
        helperReference r `shouldBe` "quote-check"
        helperBlockhash r `shouldBe` hash
        helperPayout r `shouldBe` True
        (helperOwner r,helperRecipient r) `shouldBe` (custody,wallet)
        pure payout
      call method params=case (method,params) of
        ("getLatestBlockhash",_) -> pure $ contextContract $ object ["blockhash" .= hash,"lastValidBlockHeight" .= (1000::Int)]
        ("getBlockHeight",_) -> pure (Number 900)
        ("getMultipleAccounts",[addresses,options]) -> do
          addresses `shouldBe` toJSON [wallet,replyDestination payout,custodyAta c,custody]
          fieldValue "minContextSlot" options `shouldReturn` (100::Int)
          pure $ contextContract $ toJSON [systemContract 1000000,tokenContract c wallet,tokenContract c custody,systemContract 10000000]
        ("getFeeForMessage",[message,options]) -> do
          message `shouldBe` toJSON (replyMessage payout)
          fieldValue "minContextSlot" options `shouldReturn` (100::Int)
          pure $ contextContract $ Number 5000
        ("getMinimumBalanceForRentExemption",[Number 165,_]) -> pure (Number 1488440)
        ("simulateTransaction",[transaction,options]) -> do
          transaction `shouldBe` toJSON (replyTransaction payout)
          fieldValue "sigVerify" options `shouldReturn` False
          fieldValue "replaceRecentBlockhash" options `shouldReturn` False
          fieldValue "minContextSlot" options `shouldReturn` (100::Int)
          pure $ contextContract $ object ["err" .= Null]
        _ -> expectationFailure ("unexpected quote RPC: "<>T.unpack method) >> pure Null
  action c request call helper

changeAdmissionAccount :: SolanaRPC -> Int -> (Value -> Value) -> SolanaRPC
changeAdmissionAccount call index change method params=do
  result<-call method params
  if method/="getMultipleAccounts" then pure result else do
    accounts<-fieldValue "value" result :: IO [Value]
    pure $ setPath ["value"] (toJSON [if i==index then change a else a | (i,a)<-zip [0..] accounts]) result

systemContract :: Integer -> Value
systemContract lamports=object ["owner" .= ("11111111111111111111111111111111"::Text),"executable" .= False,"data" .= ["","base64"::Text],"lamports" .= lamports]
tokenContract :: Config -> Text -> Value
tokenContract c owner=object ["owner" .= tokenProgram,"executable" .= False,"data" .= object
  ["space" .= (165::Int),"parsed" .= object ["type" .= ("account"::Text),"info" .= object
    ["mint" .= mint c,"owner" .= owner,"state" .= ("initialized"::Text),"isNative" .= False
    ,"tokenAmount" .= object ["amount" .= ("100000000000"::Text),"decimals" .= (8::Int)]]]]]
solanaContract :: Config -> SolanaPlan -> Value -> SolanaRPC
solanaContract c plan destination method _=case method of
  "getLatestBlockhash" -> pure $ contextContract $ object ["blockhash" .= recentHash (solPlanRecent plan),"lastValidBlockHeight" .= (1000::Int)]
  "getBlockHeight" -> pure (Number 900)
  "getFeeForMessage" -> pure (contextContract $ Number 5000)
  "getMultipleAccounts" -> pure $ contextContract $ toJSON [tokenContract c (custodyOwner c),destination,systemContract 10000000]
  "getMinimumBalanceForRentExemption" -> pure (Number 1488440)
  "simulateTransaction" -> pure $ contextContract $ object ["err" .= Null]
  _ -> expectationFailure ("unexpected RPC in offline contract test: "<>T.unpack method) >> pure Null

capturedCustodyAccount :: IO (Config,Value)
capturedCustodyAccount=do
  captured<-BS.readFile "test/fixtures/solana-devnet-accounts.json" >>= either fail pure . eitherDecodeStrict'
  accounts<-fieldValue "accounts" captured >>= fieldValue "value" :: IO [Value]
  account<-case accounts of _:a:_->pure a; _->fail "missing captured custody"
  pure(cfg "/unused-real-account-parser-test",account)
setPath :: [Key] -> Value -> Value -> Value
setPath [] replacement _=replacement
setPath (key:rest) replacement (Object fields)=Object $ KM.insert key (setPath rest replacement $ maybe Null id $ KM.lookup key fields) fields
setPath _ _ _=error "missing test fixture field"

capturedSolanaPayment :: String -> IO (Config,SolanaSigned,Value,SolanaOutcome)
capturedSolanaPayment kind=do
  fixtureValue<-BS.readFile ("test/fixtures/solana-devnet-"<>kind<>"-payment.json") >>= either fail pure . eitherDecodeStrict'
  signed<-fieldValue "signed" fixtureValue
  proof<-fieldValue "transaction" fixtureValue
  outcome<-fieldValue "outcome" fixtureValue
  let c=(cfg "/unused-real-payment-parser-test"){deploymentId="l2l-devnet-local",nativeWallet="ecx-bridge-test"
        ,custodyAta="CKXz4AWgfRjw5YK17P64TgXuaci2QKAD7J1vZ9X2mNvT",maxSolFee=amt 10000}
  pure(c,signed,proof,outcome)

-- Entirely offline execution tests. Only the SDK's published deterministic
-- codec key is used; these fixtures are never sent to or counted as a network.
sdkFixture :: FilePath -> IO (Config,HelperRequest,HelperReply,HelperReply)
sdkFixture library = do
  value <- BS.readFile "test/fixtures/admission-unsigned.json" >>= either fail pure . eitherDecodeStrict'
  deployment <- fieldValue "deploymentId" value
  token <- fieldValue "mint" value
  custody <- fieldValue "custodyOwner" value
  wallet <- fieldValue "wallet" value
  hash <- fieldValue "blockhash" value
  deposit <- fieldValue "deposit" value
  payout <- fieldValue "payout" value
  let c=(cfg "/nonexistent-private-config"){deploymentId=deployment,mint=token,custodyOwner=custody
        ,custodyAta=replySource payout,solanaSdkLibrary=library}
  pure (c,HelperRequest False wallet custody (amt 3) hash "quote-check",deposit,payout)

writeCodecKey :: FilePath -> IO ()
writeCodecKey filename = case Ed.secretKey (BS.replicate 32 1) of
  CryptoFailed _->error "invalid fixed codec key"
  CryptoPassed secret->do
    let public=BA.convert(Ed.toPublic secret) :: BS.ByteString
    LBS.writeFile filename (encode $ BS.unpack (BS.replicate 32 1<>public))
    setFileMode filename 0o600
main :: IO ()
main=hspec $ do
  describe "native signing RPC access control (transport contract)" $ do
    it "recognizes whitelist refusal without requiring a JSON error body" $
      testWithApplication (pure $ \_ respond->respond $ responseLBS status403 [] "") $ \port->do
        manager <- newRpcManager
        rpc manager ("http://127.0.0.1:"<>show port) Nothing "walletprocesspsbt" []
          `shouldThrow` isError "rpc_method_forbidden"
  describe "native wallet authority (offline RPC contracts)" $ do
    it "checks observation readiness without requiring signing credentials" $ property $
      \(sameName :: Bool) (descriptors :: Bool) (scanning :: Bool)->ioProperty $ do
        let c=cfg "/unused-wallet-contract"
            wallet=object ["walletname" .= (if sameName then nativeWallet c else "another-wallet")
              ,"descriptors" .= descriptors,"scanning" .= scanning]
            call scoped method params=do
              (scoped,method,params) `shouldBe` (True,"getwalletinfo",[])
              pure wallet
            expected=sameName && descriptors && not scanning
        result <- try (nativeWalletInfoWith call c) :: IO (Either BridgeError Value)
        pure $ case result of
          Right value->expected && value==wallet
          Left (BridgeError code)->not expected && code=="native_wallet_not_ready"
    it "requires local private keys and an unexpired unlock for signing readiness" $ property $
      \(keys :: Bool) (external :: Bool)->forAll (elements [Nothing,Just 0,Just 99,Just 100,Just 101]) $ \unlocked->ioProperty $ do
        let c=cfg "/unused-wallet-contract"
            wallet=object (["walletname" .= nativeWallet c,"descriptors" .= True,"scanning" .= False
              ,"private_keys_enabled" .= keys,"external_signer" .= external]
              <>maybe [] (\n->["unlocked_until" .= (n::Int64)]) unlocked)
            call scoped method params=do
              (scoped,method,params) `shouldBe` (True,"getwalletinfo",[])
              pure wallet
            expected=keys && not external && maybe True (>100) unlocked
        result <- try (nativeWalletReadyWith call c 100) :: IO (Either BridgeError ())
        pure $ case result of
          Right ()->expected
          Left (BridgeError code)->not expected && code=="native_wallet_not_ready"
  describe "operator configuration boundaries" $ do
    it "preserves deployment identity after removing the unused SQLite setting" $ do
      let c=cfg "/tmp/config-policy"
      eitherDecode (encode c) `shouldBe` Right c
      fingerprint c `shouldBe` "e000426dd3543bf975bbe89250ec03c146ce5280167ea2fa7818865db6cb9b93"
    it "rejects retired storage and helper settings instead of silently ignoring them" $ property $
      forAll (elements ["dbPath","helperPath","helperConfig"]) $ \name->
        let obsolete=setPath [name] (String "/unused/legacy") (toJSON $ cfg "/tmp/config-policy")
        in case eitherDecode (encode obsolete) :: Either String Config of Left _->True; Right _->False
    it "rejects aliases of the primary RPC as an independent provider" $ do
      forM_ ["https://api.devnet.solana.com/other", "https://api.devnet.solana.com?key=other",
             "https://api.devnet.solana.com:443", "https://API.DEVNET.SOLANA.COM",
             "https://api.devnet.solana.com."] $ \endpoint ->
        validateConfig (cfg "/tmp/config-policy"){solanaVerifierRpc=Just endpoint}
          `shouldThrow` isError "independent_rpc_required"
    it "accepts distinct actual Devnet provider hosts without network IO" $
      validateConfig (cfg "/tmp/config-policy"){solanaVerifierRpc=Just "https://solana-devnet.api.onfinality.io/public"}
    it "refuses mainnet trading links on a Devnet deployment" $ withDir $ \dir->do
      let links=(defaultInterface L2LSignetDevnet){jupiterUrl=Just "https://jup.ag/swap/SOL-token"}
      validateInterface (cfg dir) links `shouldThrow` isError "trading_links_require_mainnet"
    it "refuses script URLs, credential-bearing URLs and malformed explorer prefixes" $ withDir $ \dir->do
      let c=cfg dir; links=defaultInterface L2LSignetDevnet
      forM_ ["javascript:alert(1)","https://user:secret@example.com/support"] $ \url->
        validateInterface c links{supportUrl=Just url} `shouldThrow` isError "invalid_support_url"
      validateInterface c links{nativeExplorerBase=Just "https://example.com/tx/?key="} `shouldThrow` isError "invalid_native_explorer"
    it "validates a custody keypair against its derived public key without signing" $ withDir $ \dir->do
      case Ed.secretKey (BS.replicate 32 7) of
        CryptoFailed _->expectationFailure "fixture secret rejected"
        CryptoPassed secret->do
          let public=BA.convert(Ed.toPublic secret)::BS.ByteString
              filename=dir</>"signer.json"
              c=(cfg dir){custodyOwner=base58 public}
              writeKey bytes=LBS.writeFile filename (encode $ BS.unpack bytes) >> setFileMode filename 0o600
          writeKey (BS.replicate 32 7<>public)
          Maintenance.verifySigner c filename
          writeKey (BS.replicate 32 8<>public)
          Maintenance.verifySigner c filename `shouldThrow` isError "signer_mismatch"
          writeKey (BS.replicate 32 7<>public)
          setFileMode filename 0o644
          Maintenance.verifySigner c filename `shouldThrow` isError "unsafe_signer_permissions"
  describe "exact amounts" $ do
    it "rejects floats, exponents, leading zeros, signs, overflow and extra precision" $ do
      forM_ ["", "01", "-1", "+1", "1e8", "1.0", "9223372036854775808"] $ \s -> parseUnits s `shouldSatisfy` either (const True) (const False)
      forM_ ["1e3",".5","01.2","0.000000001","-0.1","1."] $ \s -> parseCoins s `shouldSatisfy` either (const True) (const False)
      (eitherDecodeStrict' "3"::Either String Amount) `shouldSatisfy` either (const True) (const False)
    it "preserves one and three atomic units" $ do
      parseCoins "0.00000001" `shouldBe` Right (amt 1)
      parseCoins "0.00000003" `shouldBe` Right (amt 3)
      nativeAmount (scientific 3 (-8)) `shouldBe` Right (amt 3)
      nativeAmount (scientific 1 (-1000000000)) `shouldBe` Left "native_amount_out_of_range"
    it "conserves principal and bounds upward rounding in both directions" $ property $ forAll (chooseInteger (1000,1000000000000)) $ \n -> all (valid n) [NativeToWrapped,WrappedToNative]
    it "never quotes an input consumed entirely by its fee" $ makeQuote NativeToWrapped (amt 1) `shouldBe` Left "nonpositive_net"
  describe "Solana history pagination (transport contract tests)" $ do
    it "reads multiple pages through the exact saved anchor in durable order" $ do
      calls<-newIORef []
      let row n=SignatureInfo ("signature-"<>T.pack(show n)) n False
          fetch before=do
            modifyIORef' calls (<>[before])
            pure $ case before of
              Nothing -> map row [205,204..106]
              Just "signature-106" -> map row [105,104..6]
              Just "signature-6" -> map row [5,4..1]
              _ -> []
      found<-collectSignatures "signature-1" (Just "signature-3") fetch
      map historySlot found `shouldBe` [3..205]
      readIORef calls `shouldReturn` [Nothing,Just "signature-106",Just "signature-6"]
    it "rejects an empty/truncated history without the known anchor" $ do
      let fetch Nothing=pure [SignatureInfo "recent" 20 False]
          fetch _=pure []
      collectSignatures "known-origin" Nothing fetch `shouldThrow` isError "solana_history_gap"
    it "detects repeated provider pages instead of accepting a false cursor" $ do
      collectSignatures "known-origin" Nothing (const $ pure [SignatureInfo "repeated" 20 False])
        `shouldThrow` isError "solana_history_repeated_page"
    it "rejects a nonfinalized signature-history response" $ do
      let value=object ["signature" .= base58 (BS.replicate 64 1),"slot" .= (10::Int),"confirmationStatus" .= ("confirmed"::Text),"err" .= Null]
      (parseEither parseJSON value::Either String SignatureInfo) `shouldSatisfy` either (const True) (const False)
  describe "bounded rate-limit recovery (offline transport contracts)" $ do
    it "retries read-only requests with bounded waits and honors numeric Retry-After" $ do
      calls<-newIORef (0::Int)
      delays<-newIORef []
      let action=do
            n<-atomicModifyIORef' calls (\x->(x+1,x))
            pure $ if n==0 then Left (Just 5) else if n==1 then Left Nothing else Right True
      retryRateLimitedRead (\n->modifyIORef' delays (<>[n])) "getTransaction" action `shouldReturn` True
      readIORef calls `shouldReturn` 3
      readIORef delays `shouldReturn` [5000000,8000000]
    it "does not retry sends, wallet mutations, unknown methods, or indefinite throttling" $ do
      forM_ ["sendTransaction","sendrawtransaction","walletprocesspsbt","getnewaddress","futureMethod"] $ \method -> do
        calls<-newIORef (0::Int)
        let action=modifyIORef' calls (+1) >> pure (Left Nothing :: Either (Maybe Int) ())
        retryRateLimitedRead (const $ expectationFailure "unexpected wait") method action `shouldThrow` isError "rpc_rate_limited"
        readIORef calls `shouldReturn` 1
      calls<-newIORef (0::Int)
      retryRateLimitedRead (const $ pure ()) "getTransaction" (modifyIORef' calls (+1) >> pure (Left Nothing :: Either (Maybe Int) ()))
        `shouldThrow` isError "rpc_rate_limited"
      readIORef calls `shouldReturn` 3
      retryRateLimitedRead (const $ expectationFailure "unbounded wait") "getTransaction" (pure (Left (Just 60) :: Either (Maybe Int) ()))
        `shouldThrow` isError "rpc_rate_limited"
  describe "SOL accounting from captured public Devnet metadata" $ do
    it "observes the actual SOL setup receipt without charging the external payer's fee to custody" $ do
      captured<-BS.readFile "test/fixtures/solana-devnet-accounts.json" >>= either fail pure . eitherDecodeStrict'
      sig<-fieldValue "manifest" captured >>= fieldValue "setupSignature"
      proof<-fieldValue "setupTransaction" captured
      effect<-either (fail . T.unpack) pure (lamportEffect sig (custodyOwner $ cfg "/unused") proof)
      lamportBefore effect `shouldBe` amt 0
      lamportDelta effect `shouldBe` 5000000
      lamportFee effect `shouldBe` amt 0
    forM_ [("existing",5000),("new",1493440)] $ \(kind,debit) -> it ("observes fee and account-rent SOL for the "<>kind<>" recipient") $ do
      (c,signed,proof,_)<-capturedSolanaPayment kind
      sig<-maybe (fail "missing signature") pure (replySignature $ signedSolanaReply signed)
      effect<-either (fail . T.unpack) pure (lamportEffect sig (custodyOwner c) proof)
      lamportDelta effect `shouldBe` negate debit
      lamportFee effect `shouldBe` amt 5000
    it "retains failed-transaction fees but rejects a failed transaction changing other principal" $ do
      (c,signed,proof,_)<-capturedSolanaPayment "existing"
      sig<-maybe (fail "missing signature") pure (replySignature $ signedSolanaReply signed)
      let failed=setPath ["meta","err"] (String "fixture-error") proof
      lamportFailed <$> lamportEffect sig (custodyOwner c) failed `shouldBe` Right True
      (newConfig,newSigned,newProof,_)<-capturedSolanaPayment "new"
      newSig<-maybe (fail "missing signature") pure (replySignature $ signedSolanaReply newSigned)
      lamportEffect newSig (custodyOwner newConfig) (setPath ["meta","err"] (String "fixture-error") newProof)
        `shouldBe` Left "unclassified_lamport_effect"
  describe "native quote admission (offline RPC contracts)" $ do
    it "checks the full native refund and exact net redemption without signing or locking" $ withNativeAdmission $ \c plan calls call -> do
      let wrap=req{refund=planRecipient plan}
          redeem=req{direction=WrappedToNative,input=amt 101011,recipient=planRecipient plan}
      checkNativeQuoteWith call c wrap `shouldReturn` ()
      checkNativeQuoteWith call c redeem `shouldReturn` ()
      methods<-readIORef calls
      methods `shouldSatisfy` all (`notElem` ["getnewaddress","getrawchangeaddress","lockunspent","walletprocesspsbt","finalizepsbt","sendrawtransaction"])
      length (filter (=="walletcreatefundedpsbt") methods) `shouldBe` 2
    it "rejects owned and watched destinations before wallet funding" $ withNativeAdmission $ \c plan calls call -> do
      forM_ [(True,False),(False,True)] $ \(mine,watched) -> do
        let owned wallet method params = if method=="getaddressinfo"
              then pure $ object ["ismine" .= mine,"iswatchonly" .= watched,"scriptPubKey" .= planRecipientScript plan]
              else call wallet method params
        checkNativeQuoteWith owned c req{refund=planRecipient plan} `shouldThrow` isError "bridge_owned_destination"
      readIORef calls `shouldReturn` []
    it "refuses unknown witness, anchor and nonstandard destination types" $ withNativeAdmission $ \c plan calls call -> do
      forM_ ["witness_unknown","anchor","nonstandard","nulldata","multisig"] $ \kind -> do
        let unsupported wallet method params = if method=="decodescript" then pure (object ["type" .= (kind::Text)]) else call wallet method params
        checkNativeQuoteWith unsupported c req{refund=planRecipient plan} `shouldThrow` isError "unsupported_native_destination"
      readIORef calls >>= (`shouldSatisfy` notElem "walletcreatefundedpsbt")
    it "rejects invalid address bounds and malformed script responses" $ withNativeAdmission $ \_ plan _ call -> do
      forM_ ["",T.replicate 129 "x"] $ \address -> validateNativeRecipientWith call address `shouldThrow` isError "invalid_native_address"
      forM_ ["", "0", "zz", T.replicate 202 "0"] $ \script -> do
        let malformed _ _ _=pure $ object ["ismine" .= False,"scriptPubKey" .= (script::Text)]
        validateNativeRecipientWith malformed (planRecipient plan) `shouldThrow` isError "invalid_native_script"
    it "requires a safe confirmed spendable wallet output for existing change" $ withNativeAdmission $ \c plan calls call -> do
      forM_ (["safe","spendable","solvable"]::[Text]) $ \flag -> do
        let noFunds wallet method params = if method=="listunspent"
              then pure $ toJSON [object ["address" .= planChange plan,"confirmations" .= (1000::Int)
                ,"safe" .= (flag/="safe"),"spendable" .= (flag/="spendable"),"solvable" .= (flag/="solvable")]]
              else call wallet method params
        checkNativeQuoteWith noFunds c req{refund=planRecipient plan} `shouldThrow` isError "native_admission_funds_unavailable"
      readIORef calls >>= (`shouldSatisfy` notElem "walletcreatefundedpsbt")
    it "does not touch locks belonging to another or interrupted payment" $ withNativeAdmission $ \c plan calls call -> do
      let locked wallet method params = if method=="listlockunspent"
            then pure $ toJSON [Outpoint (T.replicate 64 "a") 0] else call wallet method params
      checkNativeQuoteWith locked c req{refund=planRecipient plan} `shouldThrow` isError "native_preparation_locks_require_review"
      readIORef calls >>= (`shouldSatisfy` all (`notElem` ["lockunspent","walletcreatefundedpsbt"]))
    it "preserves a node refusal or unknown funding response without retrying or signing" $ withNativeAdmission $ \c plan calls call -> do
      forM_ ["rpc_error_-4","rpc_transport_unknown_outcome"] $ \code -> do
        writeIORef calls []
        let refused wallet method params = if method=="walletcreatefundedpsbt"
              then modifyIORef' calls (<>[method]) >> reject code else call wallet method params
        checkNativeQuoteWith refused c req{refund=planRecipient plan} `shouldThrow` isError code
        methods<-readIORef calls
        length (filter (=="walletcreatefundedpsbt") methods) `shouldBe` 1
        methods `shouldSatisfy` notElem "walletprocesspsbt"
    it "refuses funding above the native fee ceiling without changing the quoted output" $ withNativeAdmission $ \c plan calls call -> do
      checkNativeQuoteWith call c{maxNativeFee=amt 281} req{refund=planRecipient plan} `shouldThrow` isError "native_fee_mismatch"
      readIORef calls >>= (`shouldSatisfy` notElem "walletprocesspsbt")
  describe "native transaction validation (captured public-Signet transaction)" $ do
    it "accepts the exact recipient, change, input and fee in the recorded real payment" $ do
      (plan,previous,fee,tx)<-nativeFixture
      validateNativeTx plan previous fee tx `shouldBe` Right ()
      nativeTxid tx `shouldBe` "b2278e8dd0be7be001a5630545ddb73c83423ee1ee7dbd0327675e27f1642bd3"
    it "rejects changed amounts, destinations, third outputs and nonowned change scripts" $ do
      (plan,previous,fee,tx)<-nativeFixture
      let mutations=[plan{planAmount=amt 100001},plan{planRecipientScript="0014"<>T.replicate 40 "a"},plan{planChangeScript="0014"<>T.replicate 40 "b"}]
      forM_ mutations $ \changed->validateNativeTx changed previous fee tx `shouldBe` Left "native_output_mismatch"
      validateNativeTx plan previous fee tx{nativeOutputs=nativeOutputs tx<>[NativeOutput "6a00" (amt 1)]} `shouldBe` Left "native_output_mismatch"
    it "computes fees from verified prevouts and rejects unconfirmed or duplicate inputs" $ do
      (plan,previous,fee,tx)<-nativeFixture
      validateNativeTx plan{planFeeLimit=amt 281} previous fee tx `shouldBe` Left "native_fee_mismatch"
      validateNativeTx plan previous (amt 283) tx `shouldBe` Left "native_fee_mismatch"
      validateNativeTx plan (map (\p->p{prevoutAmount=amt 2000001}) previous) fee tx `shouldBe` Left "native_fee_mismatch"
      validateNativeTx plan (map (\p->p{prevoutDepth=0}) previous) fee tx `shouldBe` Left "native_input_not_confirmed"
      validateNativeTx plan (previous<>previous) fee tx{nativeInputs=nativeInputs tx<>nativeInputs tx} `shouldBe` Left "native_input_mismatch"
    it "enforces separate Signet and ECX locktime rules (pure mutation checks, not ECX acceptance)" $ do
      (plan,previous,fee,tx)<-nativeFixture
      validateNativeTx plan previous fee tx{nativeLocktime=499999999} `shouldBe` Left "native_replay_policy_mismatch"
      validateNativeTx plan{planProfile=ECXBetanetDevnet} previous fee tx `shouldBe` Left "native_replay_policy_mismatch"
      validateNativeTx plan{planProfile=ECXBetanetDevnet} previous fee tx{nativeLocktime=499999999} `shouldBe` Right ()
      validateNativeTx plan previous fee tx{nativeInputs=map (\i->i{nativeSequence=4294967295}) (nativeInputs tx)} `shouldBe` Left "native_replay_policy_mismatch"
    it "refuses a corrupted saved draft before invoking the wallet signer" $ do
      (plan,previous,fee,tx)<-nativeFixture
      let draft=NativeDraft "unused-transport-fixture" tx{nativeLocktime=1} previous fee
          unexpected _ _ _=expectationFailure "unexpected wallet RPC" >> pure Null
      signNativeDraft unexpected plan draft `shouldThrow` isError "native_replay_policy_mismatch"
  describe "Solana preparation (SDK fixtures and RPC contract tests)" $ do
    it "binds the helper protocol, message, memo, signature and custody account" $ do
      (c,plan,reply)<-solanaFixture
      let request=solanaPayoutRequest c plan
      validateHelperReply c request reply `shouldSatisfy` either (const False) (const True)
      forM_ [reply{replyProtocol=2},reply{replyMemo="wrong"},reply{replySignature=Nothing}
        ,reply{replySource=replyDestination reply},reply{replyMessage="AAAA"}] $ \changed ->
          validateHelperReply c request changed `shouldSatisfy` either (const True) (const False)
      validateHelperReply c request{helperAmount=amt 2} reply `shouldSatisfy` either (const True) (const False)
    it "simulates the exact SDK message without exposing its valid signature" $ do
      (c,plan,reply)<-solanaFixture
      calls<-newIORef []
      let call method params=do
            modifyIORef' calls (<>[method])
            case (method,params) of
              ("getFeeForMessage",[message,_])->message `shouldBe` toJSON (replyMessage reply)
              ("simulateTransaction",[String encoded,options])->do
                transaction<-either (fail . T.unpack) pure (decodeTransaction encoded)
                case transaction of
                  Transaction signatures _ body -> do
                    signatures `shouldBe` [BS.replicate 64 0]
                    TE.decodeUtf8 (B64.encode body) `shouldBe` replyMessage reply
                fieldValue "sigVerify" options `shouldReturn` False
                fieldValue "replaceRecentBlockhash" options `shouldReturn` False
              _->pure ()
            solanaContract c plan Null method params
      signed<-prepareSolanaSigned call (const $ pure reply) c plan
      signedSolanaFeeEstimate signed `shouldBe` amt 5000
      signedSolanaRentEstimate signed `shouldBe` amt 1488440
      readIORef calls >>= (`shouldSatisfy` notElem "sendTransaction")
    it "charges no rent for an existing ATA and credits lamports pre-funded to a new ATA" $ do
      (c,plan,reply)<-solanaFixture
      let prepare destination=prepareSolanaSigned (solanaContract c plan destination) (const $ pure reply) c plan
      existing<-prepare (tokenContract c (solPlanRecipient plan))
      signedSolanaRentEstimate existing `shouldBe` amt 0
      prefunded<-prepare (systemContract 100000)
      signedSolanaRentEstimate prefunded `shouldBe` amt 1388440
      full<-prepare (systemContract 2000000)
      signedSolanaRentEstimate full `shouldBe` amt 0
    it "refuses excess rent/fees, missing fee quotes and insufficient operating SOL" $ do
      (c,plan,reply)<-solanaFixture
      let prepare p transport=prepareSolanaSigned transport (const $ pure reply) c p
          call=solanaContract c plan Null
          missingFee method params=if method=="getFeeForMessage" then pure (contextContract Null) else call method params
          noSol method params=if method=="getMultipleAccounts" then pure (contextContract $ toJSON [tokenContract c (custodyOwner c),Null,systemContract 1]) else call method params
      prepare plan{solPlanRentLimit=amt 1} call `shouldThrow` isError "solana_rent_above_limit"
      prepare plan{solPlanFeeLimit=amt 1} call `shouldThrow` isError "solana_fee_above_limit"
      prepare plan missingFee `shouldThrow` isError "solana_fee_unavailable"
      prepare plan noSol `shouldThrow` isError "insufficient_operating_sol"
    it "refuses short-lived blockhashes, stale account context and failed simulation" $ do
      (c,plan,reply)<-solanaFixture
      let call=solanaContract c plan Null
          prepare rpcCall=prepareSolanaSigned rpcCall (const $ pure reply) c plan
          expired method params=if method=="getBlockHeight" then pure (toJSON (970::Int)) else call method params
          stale method params=if method=="getMultipleAccounts" then pure (object ["context" .= object ["slot" .= (99::Int)],"value" .= Null]) else call method params
          failed method params=if method=="simulateTransaction" then pure (contextContract $ object ["err" .= ("fixture-error"::Text)]) else call method params
      prepare expired `shouldThrow` isError "solana_blockhash_window_too_short"
      prepare stale `shouldThrow` isError "solana_context_too_old"
      prepare failed `shouldThrow` isError "solana_simulation_failed"
  describe "Solana quote admission (offline official-SDK and RPC contracts)" $ do
    it "checks the exact net payout using only unsigned messages" $ withSolanaAdmission $ \c request call helper ->
      checkSolanaQuoteWith call helper c request `shouldReturn` ()
    it "admits an unfunded wrap recipient and missing ATA within the rent ceiling" $ withSolanaAdmission $ \c request call helper -> do
      let missing=changeAdmissionAccount (changeAdmissionAccount call 0 (const Null)) 1 (const Null)
      checkSolanaQuoteWith missing helper c{maxSolAccountRent=amt 1488440} request `shouldReturn` ()
    it "deducts only existing system-account lamports from ATA rent" $ withSolanaAdmission $ \c request call helper -> do
      let prefunded=changeAdmissionAccount call 1 (const $ systemContract 1000000)
      checkSolanaQuoteWith prefunded helper c{maxSolAccountRent=amt 488440} request `shouldReturn` ()
      checkSolanaQuoteWith prefunded helper c{maxSolAccountRent=amt 488439} request `shouldThrow` isError "solana_rent_above_limit"
    it "rejects custody identities and mismatched source owners before any IO" $ withSolanaAdmission $ \c request _ _ -> do
      let noCall _ _=expectationFailure "RPC before owner binding" >> pure Null
          noHelper _=expectationFailure "helper before owner binding" >> reject "unexpected"
          check=checkSolanaQuoteWith noCall noHelper c
      forM_ [custodyOwner c,custodyAta c,mint c] $ \bad ->
        check request{recipient=bad} `shouldThrow` isError "bridge_owned_destination"
      check request{sourceOwner=Just $ recipient request} `shouldThrow` isError "invalid_solana_owner_binding"
      check request{direction=WrappedToNative} `shouldThrow` isError "invalid_solana_owner_binding"
      check request{recipient=T.replicate 1000 "a"} `shouldThrow` isError "invalid_public_key"
    it "rejects token, nonce and executable accounts passed as wallet owners" $ withSolanaAdmission $ \c request call helper -> do
      let bad=[tokenContract c (recipient request),setPath ["data"] (toJSON ["AA==","base64"::Text]) (systemContract 10000)
            ,setPath ["executable"] (Bool True) (systemContract 10000)]
      forM_ bad $ \wallet -> checkSolanaQuoteWith (changeAdmissionAccount call 0 $ const wallet) helper c request
        `shouldThrow` isError "unsupported_system_account"
    it "rejects wrong-owner, frozen, delegated and extended recipient accounts" $ withSolanaAdmission $ \c request call helper -> do
      let info=["data","parsed","info"]
          bad=[(info<>["owner"],toJSON $ custodyOwner c),(info<>["state"],String "frozen")
            ,(info<>["delegate"],toJSON $ custodyOwner c),(info<>["closeAuthority"],toJSON $ custodyOwner c)
            ,(["data","space"],Number 166),(["owner"],String "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")]
      forM_ bad $ \(path,value) -> checkSolanaQuoteWith (changeAdmissionAccount call 1 $ setPath path value) helper c request
        `shouldThrow` (const True :: BridgeError -> Bool)
    it "rejects insufficient custody tokens or operating SOL" $ withSolanaAdmission $ \c request call helper -> do
      checkSolanaQuoteWith (changeAdmissionAccount call 2 $ setPath ["data","parsed","info","tokenAmount","amount"] (String "2")) helper c request
        `shouldThrow` isError "insufficient_custody_tokens"
      checkSolanaQuoteWith (changeAdmissionAccount call 3 $ const $ systemContract 4999) helper c request
        `shouldThrow` isError "insufficient_operating_sol"
    it "rejects fee/rent over budget and unavailable fee estimates" $ withSolanaAdmission $ \c request call helper -> do
      checkSolanaQuoteWith call helper c{maxSolFee=amt 4999} request `shouldThrow` isError "solana_fee_above_limit"
      checkSolanaQuoteWith (changeAdmissionAccount call 1 $ const Null) helper c{maxSolAccountRent=amt 1488439} request
        `shouldThrow` isError "solana_rent_above_limit"
      let noFee method params=if method=="getFeeForMessage" then pure (contextContract Null) else call method params
      checkSolanaQuoteWith noFee helper c request `shouldThrow` isError "solana_fee_unavailable"
    it "refuses stale/incomplete account responses and failed simulation" $ withSolanaAdmission $ \c request call helper -> do
      forM_ [("getMultipleAccounts",setPath ["context","slot"] (Number 99) (contextContract $ toJSON ([]::[Value])),"solana_context_too_old")
            ,("getMultipleAccounts",contextContract (toJSON ([]::[Value])),"solana_account_snapshot_incomplete")
            ,("simulateTransaction",contextContract (object ["err" .= ("fixture-error"::Text)]),"solana_simulation_failed")] $ \(method,value,err) -> do
        let altered name params=if name==method then pure value else call name params
        checkSolanaQuoteWith altered helper c request `shouldThrow` isError err
    it "rejects signed or altered preview bytes before account reads/simulation" $ withSolanaAdmission $ \c request call helper -> do
      let badHelper r=do
            reply<-helper r
            bytes<-either fail pure (B64.decode $ TE.encodeUtf8 $ replyTransaction reply)
            pure reply{replyTransaction=TE.decodeUtf8 $ B64.encode (BS.take 1 bytes<>BS.singleton 1<>BS.drop 2 bytes)}
          noAccounts method params=if method=="getMultipleAccounts" then expectationFailure "account read after invalid preview" >> pure Null else call method params
      checkSolanaQuoteWith noAccounts badHelper c request `shouldThrow` isError "signature_shape_mismatch"
    it "rechecks the blockhash after simulation" $ withSolanaAdmission $ \c request call helper -> do
      simulated<-newIORef False
      let aging method params=do
            when (method=="simulateTransaction") $ writeIORef simulated True
            done<-readIORef simulated
            if method=="getBlockHeight" && done then pure (Number 970) else call method params
      checkSolanaQuoteWith aging helper c request `shouldThrow` isError "solana_blockhash_window_too_short"
  describe "token account policy (captured finalized Devnet accounts)" $ do
    it "accepts the real eight-decimal custody balance" $ do
      (c,account)<-capturedCustodyAccount
      inspectTokenAccount (mint c) (custodyOwner c) account `shouldBe` Right (amt 100000000000)
    it "rejects owner/mint changes, delegates, close authorities, frozen and extended accounts" $ do
      (c,account)<-capturedCustodyAccount
      let info=["data","parsed","info"]
          mutations=[(["owner"],String "wrong"),(["executable"],Bool True),(["data","space"],Number 166)
            ,(info<>["owner"],String "wrong"),(info<>["mint"],String "wrong")
            ,(info<>["delegate"],toJSON $ custodyOwner c),(info<>["closeAuthority"],toJSON $ custodyOwner c)
            ,(info<>["state"],String "frozen"),(info<>["isNative"],Bool True)
            ,(info<>["tokenAmount","decimals"],Number 9)]
      forM_ mutations $ \(path,value) ->
        inspectTokenAccount (mint c) (custodyOwner c) (setPath path value account) `shouldBe` Left "token_account_policy_mismatch"
  describe "native replacement construction (captured public templates and offline pending contracts)" $ do
    it "raises only the fee, preserving every input and the exact customer payment" $ withNativeReplacementContract $ \c original draft call calls->do
      let fee=draftFee draft
          old=signedNativeTransaction original
          new=draftTransaction draft
          customer=NativeOutput (planRecipientScript $ signedNativePlan original) (planAmount $ signedNativePlan original)
      validateNativeFamily [original] `shouldBe` Right ()
      validateNativeReplacementDraft [original] fee draft `shouldBe` Right ()
      units fee-units (signedNativeFee original) `shouldBe` 100
      nativeInputs new `shouldBe` nativeInputs old
      filter (==customer) (nativeOutputs new) `shouldBe` [customer]
      draftNativeReplacementWith call c [original] fee `shouldReturn` draft
      methods<-map fst <$> readIORef calls
      length (filter (=="createpsbt") methods) `shouldBe` 1
      methods `shouldSatisfy` all (`notElem` ["sendrawtransaction","lockunspent","getrawchangeaddress","walletcreatefundedpsbt"])
    it "rejects non-increasing fees, the immutable ceiling and exhausted change" $ withNativeReplacementContract $ \_ original _ _ _->do
      let plan=signedNativePlan original
          old=signedNativeFee original
      forM_ [old,amt $ toInteger (units old)-1,amt $ toInteger (units $ planFeeLimit plan)+1] $ \fee->
        replacementOutputs original fee `shouldBe` Left "native_replacement_fee_bounds"
      let change=sum [toInteger $ units $ nativeOutputAmount o | o<-nativeOutputs $ signedNativeTransaction original,nativeOutputScript o==planChangeScript plan]
          exhausted=amt $ toInteger (units old)+change
          enlarged=original{signedNativePlan=plan{planFeeLimit=exhausted}}
      replacementOutputs enlarged exhausted `shouldBe` Left "native_replacement_change_unavailable"
    it "cannot replace original inputs with fresh inputs even at the same value" $ withNativeReplacementContract $ \_ original draft _ _->do
      let tx=draftTransaction draft
          changed point=point{outpointTxid=nativeTxid tx}
          bad=draft{draftTransaction=tx{nativeInputs=[input{nativeOutpoint=changed $ nativeOutpoint input} | input<-nativeInputs tx]}
            ,draftPrevouts=[p{prevout=changed $ prevout p} | p<-draftPrevouts draft]}
      validateNativeTx (signedNativePlan original) (draftPrevouts bad) (draftFee bad) (draftTransaction bad) `shouldBe` Right ()
      validateNativeReplacementDraft [original] (draftFee draft) bad `shouldBe` Left "native_replacement_draft_changed"
    it "rejects changed replay fields and a changed recipient despite balanced fees" $ withNativeReplacementContract $ \_ original draft _ _->do
      let tx=draftTransaction draft
          plan=signedNativePlan original
          moved=tx{nativeOutputs=[if nativeOutputScript o==planRecipientScript plan then o{nativeOutputScript=planChangeScript plan} else o | o<-nativeOutputs tx]}
          rbf=tx{nativeInputs=[i{nativeSequence=4294967293} | i<-nativeInputs tx]}
      forM_ [tx{nativeLocktime=1},rbf] $ \bad->
        validateNativeReplacementDraft [original] (draftFee draft) draft{draftTransaction=bad} `shouldBe` Left "native_replay_policy_mismatch"
      validateNativeReplacementDraft [original] (draftFee draft) draft{draftTransaction=moved} `shouldBe` Left "native_output_mismatch"
      validateNativeFamily [] `shouldBe` Left "native_replacement_family_bounds"
      validateNativeFamily [original,original] `shouldBe` Left "native_replacement_duplicate_member"
      validateNativeFamily (replicate 9 original) `shouldBe` Left "native_replacement_family_bounds"
    it "accepts an evicted saved payment only while all exact chain inputs remain available" $ withNativeReplacementContract $ \c original draft call _->do
      let unseen wallet method params=case method of
            "gettransaction"->reject "rpc_error_-5"
            "gettxspendingprevout"->pure $ toJSON $ map (toJSON.nativeOutpoint) $ nativeInputs $ signedNativeTransaction original
            _->call wallet method params
      draftNativeReplacementWith unseen c [original] (draftFee draft) `shouldReturn` draft
    forM_ [(1,"confirmed"),(-1,"conflicted")] $ \(depth,caseName)->
      it ("refuses a "<>caseName<>" family member before constructing a PSBT") $ withNativeReplacementContract $ \c original draft call calls->do
        let changed wallet method params=do
              value<-call wallet method params
              pure $ if method=="gettransaction" then setPath ["confirmations"] (toJSON (depth::Int)) value else value
        draftNativeReplacementWith changed c [original] (draftFee draft) `shouldThrow` isError "native_replacement_member_not_pending"
        map fst <$> readIORef calls >>= (`shouldSatisfy` (not . elem "createpsbt"))
    it "refuses a mempool spender outside the saved family" $ withNativeReplacementContract $ \c original draft call _->do
      let changed wallet method params=if method=="gettxspendingprevout" then pure $ toJSON
            [object ["txid" .= outpointTxid point,"vout" .= outpointVout point,"spendingtxid" .= nativeTxid (draftTransaction draft)]
            | point<-map nativeOutpoint $ nativeInputs $ signedNativeTransaction original] else call wallet method params
      draftNativeReplacementWith changed c [original] (draftFee draft) `shouldThrow` isError "native_replacement_unknown_spender"
    it "refuses an input already spent in the active chain" $ withNativeReplacementContract $ \c original draft call _->do
      let changed wallet method params=if method=="gettxout" then pure Null else call wallet method params
      draftNativeReplacementWith changed c [original] (draftFee draft) `shouldThrow` isError "native_replacement_input_spent"
    it "refuses lagging wallet state and a wrong chain checkpoint" $ withNativeReplacementContract $ \c original draft call _->do
      let lagging wallet method params=do
            value<-call wallet method params
            pure $ if method=="getwalletinfo" then setPath ["lastprocessedblock","height"] (toJSON (16009::Int)) value else value
          wrong wallet method params=if method=="getblockhash" then pure (String $ T.replicate 64 "f") else call wallet method params
      draftNativeReplacementWith lagging c [original] (draftFee draft) `shouldThrow` isError "native_replacement_wallet_behind"
      draftNativeReplacementWith wrong c [original] (draftFee draft) `shouldThrow` isError "native_checkpoint_mismatch"
    it "discards a draft if the chain view changes while it is being built" $ withNativeReplacementContract $ \c original draft call _->do
      checks<-newIORef (0::Int)
      let changed wallet method params=do
            value<-call wallet method params
            if method/="getblockchaininfo" then pure value else do
              modifyIORef' checks (+1)
              count<-readIORef checks
              pure $ if count>1 then setPath ["bestblockhash"] (String $ T.replicate 64 "f") value else value
      draftNativeReplacementWith changed c [original] (draftFee draft) `shouldThrow` isError "native_replacement_view_changed"
    it "rejects unexpected signatures and mismatched PSBT fees" $ withNativeReplacementContract $ \c original draft call _->do
      let altered signature wallet method params=do
            value<-call wallet method params
            if method/="decodepsbt" then pure value else if signature then do
              inputs<-fieldValue "inputs" value :: IO [Value]
              pure $ setPath ["inputs"] (toJSON [setPath ["partial_signatures"] (object ["unexpected" .= ("00"::Text)]) input | input<-inputs]) value
             else pure $ setPath ["fee"] (toJSON $ nativeNumber $ amt $ toInteger (units $ draftFee draft)+1) value
      draftNativeReplacementWith (altered True) c [original] (draftFee draft) `shouldThrow` isError "native_replacement_not_unsigned"
      draftNativeReplacementWith (altered False) c [original] (draftFee draft) `shouldThrow` isError "native_replacement_draft_changed"
    it "propagates unavailable RPC evidence without allocating keys or signing" $ withNativeReplacementContract $ \c original draft call calls->do
      let unavailable wallet method params=if method=="gettxout" then reject "rpc_error_-28" else call wallet method params
      draftNativeReplacementWith unavailable c [original] (draftFee draft) `shouldThrow` isError "rpc_error_-28"
      map fst <$> readIORef calls >>= (`shouldSatisfy` (not . elem "walletprocesspsbt"))
  describe "native confirmation evidence (captured bytes and offline RPC contracts)" $ do
    it "requires the exact saved bytes and a confirmed active-chain anchor" $ do
      fixtureValue<-BS.readFile "test/fixtures/native-signet-payment.json" >>= either fail pure . eitherDecodeStrict'
      (plan,previous,fee,tx)<-nativeFixture
      raw<-fieldValue "raw" fixtureValue
      decoded<-fieldValue "decoded" fixtureValue
      let signed=NativeSigned raw tx plan previous fee
          anchor=T.replicate 64 "b"
          walletValue=object ["txid" .= nativeTxid tx,"hex" .= raw,"decoded" .= (decoded::Value)
            ,"fee" .= Number (scientific (negate $ toInteger $ units fee) (-8))
            ,"confirmations" .= (3::Int),"walletconflicts" .= ([]::[Text]),"blockhash" .= anchor]
          call _ method _=case method of
            "gettransaction"->pure walletValue
            "getblockheader"->pure $ object ["hash" .= anchor,"height" .= (123::Int),"confirmations" .= (3::Int)]
            "getblockhash"->pure (toJSON anchor)
            _->expectationFailure "unexpected native RPC" >> pure Null
      observeNativePayment call signed >>= \result -> case result of
        PaymentConfirmed costs _->costs `shouldBe` PaymentCosts fee (amt 0)
        _->expectationFailure "expected confirmed payment"
      let fork wallet method params=if method=="getblockhash" then pure (String $ T.replicate 64 "c") else call wallet method params
      observeNativePayment fork signed `shouldThrow` isError "native_settlement_not_canonical"
      let changed wallet method params=if method=="gettransaction" then pure (setPath ["hex"] (String "00") walletValue) else call wallet method params
      observeNativePayment changed signed `shouldThrow` isError "native_settlement_evidence_mismatch"
  describe "Solana settlement evidence (captured finalized public Devnet payments)" $ do
    forM_ ["existing","new"] $ \kind -> it ("validates exact bytes/units and actual costs for "<>kind<>" recipient ATA") $ do
      (c,signed,proof,outcome)<-capturedSolanaPayment kind
      verifySolanaOutcome c signed proof `shouldBe` Right outcome
      outcomeSucceeded outcome `shouldBe` True
      outcomeFee outcome `shouldBe` amt 5000
      outcomeRent outcome `shouldBe` amt (if kind=="new" then 1488440 else 0)
    it "rejects altered message/signature/slot/costs and missing token evidence" $ do
      (c,signed,proof,_)<-capturedSolanaPayment "new"
      let mutations=[(["slot"],Number 0),(["transaction","signatures"],toJSON ["wrong"::Text])
            ,(["transaction","message","recentBlockhash"],String "wrong")
            ,(["transaction","message","header","numRequiredSignatures"],Number 2)
            ,(["meta","fee"],Number 4999),(["meta","preBalances"],toJSON ([]::[Int]))
            ,(["meta","preTokenBalances"],toJSON ([]::[Value]))
            ,(["meta","postTokenBalances"],toJSON ([]::[Value]))]
      forM_ mutations $ \(path,value) -> verifySolanaOutcome c signed (setPath path value proof)
        `shouldBe` Left "solana_settlement_evidence_mismatch"
    it "rejects costs above the saved rent cap and a changed deployment" $ do
      (c,signed,proof,_)<-capturedSolanaPayment "new"
      let lowered=signed{signedSolanaPlan=(signedSolanaPlan signed){solPlanRentLimit=amt 1}}
      verifySolanaOutcome c lowered proof `shouldBe` Left "solana_settlement_evidence_mismatch"
      verifySolanaOutcome c{deploymentId="changed"} signed proof `shouldBe` Left "saved_solana_policy_mismatch"
    it "uses saved ceilings to reconcile an existing payment after future limits are lowered" $ do
      (c,signed,proof,outcome)<-capturedSolanaPayment "new"
      verifySolanaOutcome c{maxSolFee=amt 1,maxSolAccountRent=amt 0} signed proof `shouldBe` Right outcome
    it "rejects a changed token delta or historical owner and contradictory failure metadata" $ do
      (c,signed,proof,_)<-capturedSolanaPayment "existing"
      rows<-fieldValue "meta" proof >>= fieldValue "postTokenBalances" :: IO [Value]
      let changed path value=setPath ["meta","postTokenBalances"] (toJSON $ map (setPath path value) rows) proof
      forM_ [changed ["uiTokenAmount","amount"] (String "4"),changed ["owner"] (String "wrong")
        ,setPath ["meta","err"] (String "fixture-failure") proof] $ \bad ->
          verifySolanaOutcome c signed bad `shouldBe` Left "solana_settlement_evidence_mismatch"
  describe "TLS name-constraint properties" $ do
    it "accepts permitted DNS and rejects outside/excluded DNS through the real validator" $ withDir $ \dir->do
      check <- constrainedIssuer dir
      let invalidName (InvalidName _) = True
          invalidName _ = False
      check "blocked.allowed.example" >>= (`shouldSatisfy` any invalidName)
      result <- quickCheckWithResult stdArgs{maxSuccess=20} $
        forAll (chooseInt (1,12) >>= \n->vectorOf n (elements ['a'..'z'])) $ \label->ioProperty $ do
          valid <- check ("ok-"<>label<>".allowed.example")
          outside <- check (label<>".other.example")
          excluded <- check (label<>".blocked.allowed.example")
          pure $ counterexample (show (valid,outside,excluded)) $
            null valid && any invalidName outside && any invalidName excluded
      result `shouldSatisfy` isSuccess
  describe "pinned SDK properties through Cabal" $ do
    it "passes the official SDK codec and FFI boundary contracts" $ do
      (exit, _, errors) <- readProcessWithExitCode "cargo"
        ["test", "--locked", "--manifest-path", sdkSourceDirectory</>"Cargo.toml",
         "--target-dir", sdkTargetDirectory, "--lib", "-j1"] ""
      when (exit/=ExitSuccess) (expectationFailure errors)
  describe "release authentication properties" $ do
    forM_ [minBound..maxBound] $ \fault->it (show fault) $ property $ withNumTests 5 $
      forAll (vectorOf 32 arbitrary) $ \seed->forAll (elements ["aarch64","x86_64"]) $ \arch->
        ioProperty (releaseAuthentication fault seed arch)
  describe "direct public server" $ do
    it "serves assets and CustomerAPI with security headers, excluding operator routes" $ withDir $ \dir->do
      writeFile (dir</>"index.html") "<html>bridge</html>"
      app <- publicApplication dir (serve customerAPI customerFixture)
      let get path=W.runSession (W.request $ W.setPath defaultRequest path) app
      page <- get "/"
      W.simpleStatus page `shouldBe` status200
      W.simpleBody page `shouldBe` "<html>bridge</html>"
      lookup "Cache-Control" (W.simpleHeaders page) `shouldBe` Just "no-store"
      configuration <- get "/api/v1/config"
      W.simpleStatus configuration `shouldBe` status200
      forM_ ["/health","/healthz","/readyz","/scanners","/audit","/pause","/api/v1/orders/id/observations"] $ \path->get path >>= \response->
        W.simpleStatus response `shouldBe` status404
  describe "private signing Servant boundary" $ do
    it "dispatches only the three closed signing routes and rejects malformed or oversized requests before evaluation" $ do
      calls <- newIORef (0 :: Int)
      let credentials=BasicAuthData "worker" (BS.replicate 64 97)
          authorization="Basic "<>B64.encode ("worker:"<>BS.replicate 64 97)
      app <- signingApplication credentials (\_ -> modifyIORef' calls (+1) >> reject "signing_fixture")
      let post path body = W.runSession (W.srequest $ W.SRequest
            ((W.setPath defaultRequest path){requestMethod="POST",requestHeaders=[("Content-Type","application/json"),("Authorization",authorization)]}) body) app
      forM_ [("/sign-preparation",encode ("identity" :: Text,"intent" :: Text,0 :: Int)),
             ("/draft-replacement",encode ("identity" :: Text,"parent" :: Text,amt 1)),
             ("/sign-replacement",encode ("identity" :: Text,1 :: Int64))] $ \(path,body) -> do
        response <- post path body
        W.simpleStatus response `shouldBe` status409
        W.simpleBody response `shouldBe` encode (object ["error" .= ("signing_fixture" :: Text)])
      readIORef calls `shouldReturn` 3
      forM_ ["/pause","/refund","/broadcast","/sign","/audit"] $ \path ->
        post path "[]" >>= \response -> W.simpleStatus response `shouldBe` status404
      post "/sign-preparation" "{}" >>= \response -> W.simpleStatus response `shouldBe` status400
      post "/sign-preparation" (LBS.replicate 16385 32) >>= \response -> W.simpleStatus response `shouldBe` status413
      forM_ [(Nothing,status401),(Just "Basic d29ya2VyOndyb25n",status403)] $ \(authentication,expected)->do
        denied <- W.runSession (W.srequest $ W.SRequest
          ((W.setPath defaultRequest "/sign-preparation"){requestMethod="POST"
            ,requestHeaders=[("Content-Type","application/json")]<>maybe [] (\value->[("Authorization",value)]) authentication})
          (encode ("identity"::Text,"intent"::Text,0::Int))) app
        W.simpleStatus denied `shouldBe` expected
      readIORef calls `shouldReturn` 3
    it "loads only a bounded private credential file and rejects public permissions" $ withDir $ \dir->do
      let c=cfg dir
      BS.writeFile (signerAuthFile c) (BS.replicate 64 97<>"\n")
      setFileMode (signerAuthFile c) 0o600
      credentials <- signerCredentials c
      basicAuthUsername credentials `shouldBe` "worker"
      basicAuthPassword credentials `shouldBe` BS.replicate 64 97
      setFileMode (signerAuthFile c) 0o644
      signerCredentials c `shouldThrow` isError "unsafe_signer_auth_permissions"
      setFileMode (signerAuthFile c) 0o600
      BS.writeFile (signerAuthFile c) (BS.replicate 100 97)
      signerCredentials c `shouldThrow` isError "invalid_signer_auth_token"
    it "uses authenticated ClientM over TLS and rejects a different certificate" $ withDir $ \dir->do
      let c=cfg dir
          wrong=c{signerAuthFile=dir</>"wrong.auth"}
          generate configuration=do
            (code,_,_) <- readProcessWithExitCode "openssl"
              ["req","-x509","-newkey","rsa:2048","-nodes","-days","1","-subj","/CN=127.0.0.1"
              ,"-addext","subjectAltName=IP:127.0.0.1,DNS:127.0.0.1"
              ,"-keyout",signerAuthFile configuration<>".key","-out",signerAuthFile configuration<>".pem"] ""
            code `shouldBe` ExitSuccess
          credentials=BasicAuthData "worker" (BS.replicate 64 97)
      generate c
      generate wrong
      certificate <- signerCertificate c
      other <- signerCertificate wrong
      calls <- newIORef (0::Int)
      app <- signingApplication credentials (\_ -> modifyIORef' calls (+1) >> reject "signing_fixture")
      ready <- newEmptyMVar
      bracket openFreePort (NS.close . snd) $ \(port,socket)->
        withAsync (runTLSSocket (tlsSettings (signerAuthFile c<>".pem") (signerAuthFile c<>".key"))
          (setBeforeMainLoop (putMVar ready ()) defaultSettings) socket app) $ \running->do
          link running
          takeMVar ready
          let managerFor trusted=do
                let base=TLS.defaultParamsClient "127.0.0.1" BS.empty
                    params=base{TLS.clientShared=(TLS.clientShared base){TLS.sharedCAStore=makeCertificateStore [trusted]}
                      ,TLS.clientSupported=(TLS.clientSupported base){TLS.supportedCiphers=ciphersuite_default}}
                newManager (mkManagerSettings (NC.TLSSettings params) Nothing)
              environment manager=mkClientEnv manager (BaseUrl Https "127.0.0.1" port "")
              preparation :<|> draft :<|> replacement=client signingAPI credentials
              evaluated result=case result of
                Left (FailureResponse _ response)->responseStatusCode response==status409
                _->False
          bracket (managerFor certificate) closeManager $ \manager->do
            forM_ [preparation ("identity","intent",0),draft ("identity","parent",amt 1),replacement ("identity",1)] $ \action->
              runClientM action (environment manager) >>= (`shouldSatisfy` evaluated)
          readIORef calls `shouldReturn` 3
          bracket (managerFor other) closeManager $ \manager->do
            result <- runClientM (preparation ("identity","intent",0)) (environment manager)
            result `shouldSatisfy` \case Left (ConnectionError _)->True; _->False
          readIORef calls `shouldReturn` 3
  describe "public/private Unix socket boundary" $ do
    it "refuses canonical and backup-dependent deployments in the local test command" $ withDir $ \dir->do
      publicTestProfile (cfg dir) `shouldBe` True
      publicTestProfile (cfg dir){profile=ECXBetanetDevnet} `shouldBe` True
      publicTestProfile (cfg dir){profile=CanonicalBeta} `shouldBe` False
      publicTestProfile (cfg dir){backupRequired=True} `shouldBe` False
      Runtime.runTestWorker PG.defaultConnectInfo (cfg dir){profile=CanonicalBeta} `shouldThrow` isError "public_test_profile_required"
      Runtime.runTestWorker PG.defaultConnectInfo (cfg dir){backupRequired=True} `shouldThrow` isError "public_test_profile_required"
    it "uses the customer Servant contract and non-HTTP private control socket" $ withDir $ \dir -> do
      let c=cfg dir
      withAsync (socketFixture c) $ \_ -> do
        awaitFile (customerSocket c) 100
        awaitFile (adminSocket c) 100
        manager <- unixManager (customerSocket c)
        do
          let configCall :<|> createCall :<|> _ :<|> _ = client customerAPI
              env=mkClientEnv manager (BaseUrl Http "localhost" 80 "")
          configResult<-runClientM configCall env
          configResult `shouldSatisfy` either (const False) (const True)
          case configResult of
            Right value->API.pubIntakeEnabled value `shouldBe` False
            Left _->expectationFailure "configuration unavailable"
          rejected<-runClientM (createCall "Bearer invalid" req) env
          rejected `shouldSatisfy` either (const True) (const False)
          reply <- callControl c (object ["operation" .= ("audit"::Text)])
          fieldValue "error" reply `shouldReturn` ("fixture_operation_unavailable"::Text)
          invalid <- callControl c (object ["operation" .= ("arbitrary-sql"::Text)])
          fieldValue "error" invalid `shouldReturn` ("invalid_operator_operation"::Text)
        publicMode<-fileMode <$> getFileStatus (customerSocket c)
        adminMode<-fileMode <$> getFileStatus (adminSocket c)
        publicMode .&. 0o777 `shouldBe` 0o660
        adminMode .&. 0o777 `shouldBe` 0o600
    it "reconnects the first GET and POST after worker replacement without replacing the clients" $ withDir $ \dir -> do
      let c=cfg dir
          configCall :<|> createCall :<|> _ :<|> _ = client customerAPI
      reader <- unixManager (customerSocket c)
      writer <- unixManager (customerSocket c)
      let readEnv=mkClientEnv reader (BaseUrl Http "localhost" 80 "")
          writeEnv=mkClientEnv writer (BaseUrl Http "localhost" 80 "")
      withAsync (socketFixture c) $ \_ -> do
        awaitFile (customerSocket c) 100
        runClientM configCall readEnv >>= (`shouldSatisfy` either (const False) (const True))
        runClientM configCall writeEnv >>= (`shouldSatisfy` either (const False) (const True))
      -- Only fixture sockets are removed. Keeping both client managers alive
      -- across the worker's replacement reproduces the live stale-pool error.
      removeFile (customerSocket c)
      removeFile (adminSocket c)
      withAsync (socketFixture c) $ \_ -> do
        awaitFile (customerSocket c) 100
        awaitFile (adminSocket c) 100
        runClientM configCall readEnv >>= (`shouldSatisfy` either (const False) (const True))
        result <- runClientM (createCall "Bearer invalid" req) writeEnv
        result `shouldSatisfy` (\case Left (FailureResponse _ _) -> True; _ -> False)
  describe "historical Solana deposit evidence" $ do
    it "binds a Solana Pay reference to the transfer and historical owner (offline contract)" $ do
      captured <- BS.readFile "test/fixtures/solana-devnet-order-deposit.json" >>= either fail pure . eitherDecodeStrict'
      binding <- fieldValue "binding" captured
      original <- fieldValue "transaction" captured
      tx <- fieldValue "transaction" original
      message <- fieldValue "message" tx
      keys <- fieldValue "accountKeys" message :: IO [Text]
      reference <- either (fail . T.unpack) pure (Pay.payReference $ T.replicate 64 "f")
      index <- maybe (fail "memo program missing") pure (elemIndex "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr" keys)
      instructions <- fieldValue "instructions" message :: IO [Value]
      tokenInstructions <- mapM (\ix->do
        program <- fieldValue "programIdIndex" ix :: IO Int
        accounts <- fieldValue "accounts" ix :: IO [Int]
        pure (keys!!program,case ix of Object fields->Object(KM.insert "accounts" (toJSON $ accounts<>[index]) fields); _->ix)) instructions
      let proof=setPath ["transaction","message","accountKeys"] (toJSON [if i==index then reference else key | (i,key)<-zip [0..] keys]) $
            setPath ["transaction","message","instructions"] (toJSON [ix | (program,ix)<-tokenInstructions,program==tokenProgram]) original
      expected <- Pay.PayBinding <$> fieldValue "signature" binding <*> fieldValue "mint" binding
        <*> fieldValue "custody" binding <*> fieldValue "custodyOwner" binding <*> pure reference
      owner <- fieldValue "owner" binding
      verifiedOwner <$> Pay.verifyPay expected proof `shouldBe` Right owner
      Pay.verifyPay expected{Pay.payOrderReference="11111111111111111111111111111111"} proof `shouldSatisfy` either (const True) (const False)
      Pay.verifyPay expected (setPath ["transaction","message","header","numReadonlyUnsignedAccounts"] (Number 0) proof) `shouldSatisfy` either (const True) (const False)
    it "requires a unique historical token balance with the exact owner, mint and precision" $
      property $ forAll (chooseInteger (0,toInteger (maxBound::Int64))) $ \n->
        let entry=object ["accountIndex" .= (2::Int),"mint" .= ("expected-mint"::Text),"owner" .= ("expected-owner"::Text)
              ,"uiTokenAmount" .= object ["decimals" .= (8::Int),"amount" .= T.pack(show n)]]
            parse rows=parseEither (historicalTokenBalance "expected-mint" 2 "expected-owner") rows
            wrong=map (\(path,value)->[setPath path value entry])
              [(["owner"],String "other-owner"),(["mint"],String "other-mint")
              ,(["uiTokenAmount","decimals"],Number 9),(["uiTokenAmount","amount"],String "-1")]
        in conjoin [parse [entry]===Right n,property $ all (either (const True) (const False) . parse) ([]:[entry,entry]:wrong)]
    it "validates the captured real Devnet order deposit without current account lookups" $ do
      captured<-BS.readFile "test/fixtures/solana-devnet-order-deposit.json" >>= either fail pure . eitherDecodeStrict'
      binding<-fieldValue "binding" captured
      expected<-DepositBinding <$> fieldValue "signature" binding <*> fieldValue "owner" binding
        <*> fieldValue "mint" binding <*> fieldValue "custody" binding <*> fieldValue "custodyOwner" binding <*> fieldValue "memo" binding
      proof<-fieldValue "transaction" captured
      quantity<-fieldValue "expectedAmount" captured
      verified<-either (fail . T.unpack) pure (verifyDeposit expected proof)
      verifiedAmount verified `shouldBe` quantity
      verifiedSlot verified `shouldSatisfy` (>0)
    it "validates owner, mint, memo, signer and exact historical custody increase" $ do
      (binding,proof)<-depositFixture
      verifiedAmount <$> verifyDeposit binding proof `shouldBe` Right (amt 3)
      effectDelta <$> custodyEffect (boundSignature binding) (boundMint binding) (boundCustody binding) (boundCustodyOwner binding) proof `shouldBe` Right 3
      transactionMemo proof `shouldBe` Just (boundMemo binding)
    it "retains an unmatched balance increase even when automatic authorization fails" $ do
      (binding,proof)<-depositFixture
      verifyDeposit binding{boundMemo="different-order"} proof `shouldSatisfy` either (const True) (const False)
      effectDelta <$> custodyEffect (boundSignature binding) (boundMint binding) (boundCustody binding) (boundCustodyOwner binding) proof `shouldBe` Right 3
      custodyEffect (boundSignature binding) (boundMint binding) (boundCustody binding) "incorrect-owner" proof `shouldSatisfy` either (const True) (const False)
    it "resolves a version-zero custody address loaded from historical metadata" $ do
      (binding,proof)<-depositFixture
      versioned<-versionZeroFixture (boundCustody binding) proof
      keys<-either (fail . T.unpack) pure (Pay.transactionKeys versioned)
      last keys `shouldBe` boundCustody binding
      forM_ [[],keys<>take 1 keys,[T.replicate 45 "1"]] $ \invalid->
        Pay.transactionKeys (setPath ["transaction","message","accountKeys"] (toJSON invalid) proof)
          `shouldBe` Left "invalid_pay_accounts"
      verifiedAmount <$> verifyDeposit binding versioned `shouldBe` Right (amt 3)
      effectDelta <$> custodyEffect (boundSignature binding) (boundMint binding) (boundCustody binding) (boundCustodyOwner binding) versioned `shouldBe` Right 3
    it "rejects copied memos, wrong historical owners and wrong custody" $ do
      (binding,proof)<-depositFixture
      verifyDeposit binding{boundOwner="different-owner"} proof `shouldSatisfy` either (const True) (const False)
      verifyDeposit binding{boundMemo="copied"} proof `shouldSatisfy` either (const True) (const False)
      verifyDeposit binding{boundCustody="wrong-custody"} proof `shouldSatisfy` either (const True) (const False)
    it "cannot authorize a failed or unsupported-version transaction" $ do
      (binding,proof)<-depositFixture
      let setMetaError (Object p)=Object $ case KM.lookup "meta" p of
            Just (Object m)->KM.insert "meta" (Object (KM.insert "err" (String "failed") m)) p
            _->p
          setMetaError x=x
          setVersion (Object p)=Object(KM.insert "version" (Number 1) p)
          setVersion x=x
      verifyDeposit binding (setMetaError proof) `shouldSatisfy` either (const True) (const False)
      verifyDeposit binding (setVersion proof) `shouldSatisfy` either (const True) (const False)
  describe "encrypted backup command refusals (offline)" $ do
    forM_ ["local","loopback","exposed","incomplete"] $ \fault->
      it ("rejects "<>fault<>" credentials before staging, without disclosing them") $
        property $ withNumTests 5 $ forAll (vectorOf 32 $ elements ['a'..'z']) $ \secret->
          ioProperty $ withDir $ \dir->do
            setFileMode dir 0o700
            let repository=dir</>"repository"
                password=dir</>"password"
                stage=dir</>"stage"
                location=case fault of
                  "local"->dir</>"local-repository"
                  "loopback"->"rest:https://127.0.0.1/"<>secret
                  _->"rest:https://backup.example.invalid/"<>secret
                args=["-B","integration/PostgresEncryptedBackupCheck.py",dir</>"absent-manifest"
                  ,"--directory",stage,"--restic",dir</>"absent-restic","--repository-file",repository]
                  <> if fault=="incomplete" then [] else ["--password-file",password]
            writeFile password secret
            setFileMode password 0o600
            writeFile repository location
            setFileMode repository (if fault=="exposed" then 0o644 else 0o600)
            result<-timeout 10000000 $ readProcessWithExitCode "python3" args ""
            staged<-doesPathExist stage
            pure $ counterexample ("backup refusal contract: "<>fault) $ case result of
              Just (code,out,err)->code/=ExitSuccess && not staged &&
                all (\sensitive->not $ T.pack sensitive `T.isInfixOf` T.pack (out<>err)) [secret,location,"Traceback"]
              Nothing->False
  describe "Haskell / official Solana SDK FFI (offline codec contracts)" $ do
    library <- runIO (maybe sdkLibraryPath id <$> lookupEnv "ECX_SOLANA_SDK_LIBRARY")
    it "preserves captured unsigned messages without opening private configuration" $ do
      (c,request,deposit,payout) <- sdkFixture library
      invokeUnsignedHelper c request `shouldReturn` deposit
      invokeUnsignedHelper c request{helperPayout=True,helperOwner=custodyOwner c
        ,helperRecipient=helperOwner request} `shouldReturn` payout
    it "binds generated amounts/references in both directions without signatures" $
      property $ withNumTests 50 $ forAll (chooseInteger (1,toInteger (maxBound::Int64))) $ \quantity->
        forAll arbitrary $ \payout->forAll (chooseInt (1,64) >>= \n->vectorOf n (elements ['a'..'z'])) $ \reference->
          ioProperty $ do
            (c,base,_,_) <- sdkFixture library
            let request=base{helperPayout=payout,helperAmount=amt quantity,helperReference=T.pack reference
                  ,helperOwner=if payout then custodyOwner c else helperOwner base
                  ,helperRecipient=if payout then helperOwner base else custodyOwner c}
            reply <- invokeUnsignedHelper c request
            pure (replySignature reply==Nothing && case validateUnsignedHelperReply c request reply of
              Right _->True; Left _->False)
    it "signs generated saved amounts with the fixed public codec key" $
      property $ withNumTests 20 $ forAll (chooseInteger (1,toInteger (maxBound::Int64))) $ \quantity->
        ioProperty $ withDir $ \dir->do
          (base,plan,_) <- solanaFixture
          let c=base{solanaSdkLibrary=library}
              request=solanaPayoutRequest c plan{solPlanAmount=amt quantity}
              key=dir</>"signer.json"
          writeCodecKey key
          reply <- signSolanaSdk c key request
          pure (replySignature reply/=Nothing && case validateHelperReply c request reply of
            Right _->True; Left _->False)
    it "refuses a publicly readable signing key" $ withDir $ \dir->do
      (base,plan,_) <- solanaFixture
      let key=dir</>"signer.json"
      writeCodecKey key
      setFileMode key 0o644
      signSolanaSdk base{solanaSdkLibrary=library} key (solanaPayoutRequest base plan)
        `shouldThrow` isError "solana_sdk_failed"
    it "fails closed on a missing SDK library" $ do
      (c,request,_,_) <- sdkFixture "/nonexistent-ecx-sdk"
      invokeUnsignedHelper c request `shouldThrow` (\(_::SomeException)->True)
  describe "official SDK wire fixtures (not network evidence)" $ do
    forM_ ["unsigned-three-units.json","signed-three-units.json"] $ \name -> it ("independently validates "<>name) $ do
      (expected,encoded)<-fixture name
      validateTransaction expected encoded `shouldSatisfy` either (const False) (const True)
      validateTransaction expected{expectedAmount=amt 2} encoded `shouldSatisfy` either (const True) (const False)
      validateTransaction expected{expectedMemo="copied-memo"} encoded `shouldSatisfy` either (const True) (const False)
    it "rejects corrupted signed bytes" $ do
      (expected,encoded)<-fixture "signed-three-units.json"
      bytes<-either fail pure (B64.decode $ TE.encodeUtf8 encoded)
      let mutated=BS.take 4 bytes<>BS.singleton ((BS.index bytes 4+1)`mod`255)<>BS.drop 5 bytes
      validateTransaction expected (TE.decodeUtf8 $ B64.encode mutated) `shouldBe` Left "invalid_signature"
 where
  valid n d = case makeQuote d (amt n) of
    Right q -> let f=toInteger (units (fee q)); b=feeBps d in units (net q)+units (fee q)==fromInteger n && f*10000 >= n*b && (f-1)*10000<n*b
    Left _ -> False