-- PostgreSQL baseline translated from the retired SQLite schema at 6d293a3.
-- Maintain subsequent changes as reviewed forward migrations.

-- Fresh PostgreSQL financial schema; legacy schema version remains 18.

BEGIN;

CREATE FUNCTION bridge_json_valid(value text) RETURNS boolean LANGUAGE plpgsql IMMUTABLE STRICT AS $$ BEGIN PERFORM value::json; RETURN true; EXCEPTION WHEN invalid_text_representation THEN RETURN false; END $$;

CREATE TABLE orders(id TEXT PRIMARY KEY, capability_hash TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, request_json TEXT NOT NULL, quote_json TEXT NOT NULL, policy_json TEXT NOT NULL, status TEXT NOT NULL, deadline BIGINT NOT NULL, grace_deadline BIGINT NOT NULL, instruction TEXT UNIQUE, instruction_sequence BIGINT, payout_tx TEXT, instruction_issued BIGINT NOT NULL DEFAULT 0 CHECK(instruction_issued IN(0,1)), UNIQUE(capability_hash,idempotency_key));

CREATE TABLE events(id TEXT PRIMARY KEY, description TEXT NOT NULL);

CREATE TABLE checkpoints(chain TEXT PRIMARY KEY, anchor TEXT NOT NULL);

CREATE TABLE audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, action TEXT NOT NULL, detail TEXT NOT NULL);

CREATE TABLE deployment(singleton BIGINT PRIMARY KEY CHECK(singleton=1), schema_version BIGINT NOT NULL CHECK(schema_version>=1), fingerprint TEXT NOT NULL, critical_sequence BIGINT NOT NULL DEFAULT 0, backup_sequence BIGINT NOT NULL DEFAULT 0, paused BIGINT NOT NULL DEFAULT 1 CHECK(paused IN(0,1)), pause_reason TEXT NOT NULL DEFAULT 'initialization');

CREATE TABLE observation_evidence(hash TEXT PRIMARY KEY, chain TEXT NOT NULL, event_id TEXT NOT NULL, evidence_json TEXT NOT NULL);

CREATE TABLE scan_origins(chain TEXT PRIMARY KEY CHECK(chain IN('Native','Solana','SolanaOperating')), anchor TEXT NOT NULL);

CREATE TABLE scan_health(chain TEXT PRIMARY KEY CHECK(chain IN('Native','Solana','SolanaOperating')), last_success BIGINT, last_error TEXT, checked_at BIGINT NOT NULL);

CREATE TABLE operating_clock(singleton BIGINT PRIMARY KEY CHECK(singleton=1), last_time BIGINT NOT NULL CHECK(last_time>=0));

CREATE TABLE custody_check(singleton BIGINT PRIMARY KEY CHECK(singleton=1), revision BIGINT NOT NULL DEFAULT 0 CHECK(revision>=0), checked_revision BIGINT, checked_at BIGINT, last_error TEXT, report_json TEXT);

CREATE TABLE postings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), asset TEXT NOT NULL CHECK(asset IN('Native','Wrapped','Sol')), account TEXT NOT NULL, delta BIGINT NOT NULL CHECK(delta<>0));

CREATE TABLE reservations(order_id TEXT PRIMARY KEY REFERENCES orders(id), asset TEXT NOT NULL, amount BIGINT NOT NULL CHECK(amount>0), phase TEXT NOT NULL CHECK(phase IN('quote','obligation','payment','released')));

CREATE TABLE deposits(id TEXT PRIMARY KEY, order_id TEXT REFERENCES orders(id), asset TEXT NOT NULL, amount BIGINT NOT NULL CHECK(amount>0), anchor TEXT NOT NULL, first_seen BIGINT NOT NULL, confirmations BIGINT NOT NULL CHECK(confirmations>=0), eligible BIGINT NOT NULL CHECK(eligible IN(0,1)), allocated BIGINT NOT NULL DEFAULT 0 CHECK(allocated IN(0,1)), state TEXT NOT NULL DEFAULT 'observed');

CREATE TABLE hints(order_id TEXT NOT NULL REFERENCES orders(id), signature TEXT NOT NULL, PRIMARY KEY(order_id,signature));

CREATE TABLE chain_events(chain TEXT NOT NULL CHECK(chain IN('Native','Solana','SolanaOperating')), event_id TEXT NOT NULL, kind TEXT NOT NULL, anchor TEXT NOT NULL, evidence_hash TEXT NOT NULL REFERENCES observation_evidence(hash), first_seen BIGINT NOT NULL, last_seen BIGINT NOT NULL, needs_review BIGINT NOT NULL CHECK(needs_review IN(0,1)), PRIMARY KEY(chain,event_id));

CREATE TABLE order_cost_limits(order_id TEXT PRIMARY KEY REFERENCES orders(id), native_fee BIGINT NOT NULL CHECK(native_fee>0), solana_fee BIGINT NOT NULL CHECK(solana_fee>0), solana_rent BIGINT NOT NULL CHECK(solana_rent>=0));

CREATE TABLE native_allocations(order_id TEXT PRIMARY KEY REFERENCES orders(id), label TEXT NOT NULL UNIQUE, critical_sequence BIGINT NOT NULL CHECK(critical_sequence>0));

CREATE TABLE obligations(id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), deposit_id TEXT NOT NULL REFERENCES deposits(id), kind TEXT NOT NULL CHECK(kind IN('conversion','refund')), asset TEXT NOT NULL, amount BIGINT NOT NULL CHECK(amount>0), recipient TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN('ready','paying','paid','review','cancelled')));

CREATE TABLE treasury_allocations(deposit_id TEXT PRIMARY KEY REFERENCES deposits(id), allocation_json TEXT NOT NULL, proof_json TEXT NOT NULL, critical_sequence BIGINT NOT NULL);

CREATE TABLE treasury_spends(chain TEXT NOT NULL, event_id TEXT NOT NULL, anchor TEXT NOT NULL, economic_json TEXT NOT NULL, proof_json TEXT NOT NULL, critical_sequence BIGINT NOT NULL, PRIMARY KEY(chain,event_id), FOREIGN KEY(chain,event_id) REFERENCES chain_events(chain,event_id));

CREATE TABLE operating_costs(posting_id BIGINT PRIMARY KEY REFERENCES postings(id), recorded_at BIGINT NOT NULL CHECK(recorded_at>=0));

CREATE TABLE operating_reservations(order_id TEXT NOT NULL REFERENCES order_cost_limits(order_id), kind TEXT NOT NULL CHECK(kind IN('conversion','refund')), asset TEXT NOT NULL CHECK(asset IN('Native','Sol')), amount BIGINT NOT NULL CHECK(amount>0), phase TEXT NOT NULL CHECK(phase IN('quote','obligation','transferred','released')), PRIMARY KEY(order_id,kind));

CREATE TABLE source_recoveries(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, deposit_id TEXT NOT NULL REFERENCES deposits(id), state TEXT NOT NULL CHECK(state IN('pending','missing','restored','unavailable')), shortfall BIGINT NOT NULL CHECK(shortfall>=0), evidence_json TEXT NOT NULL CHECK(bridge_json_valid(evidence_json) AND length(evidence_json)<=16384), critical_sequence BIGINT NOT NULL UNIQUE CHECK(critical_sequence>0));

CREATE TABLE intents(id TEXT PRIMARY KEY, obligation_id TEXT NOT NULL UNIQUE REFERENCES obligations(id), chain TEXT NOT NULL CHECK(chain IN('Native','Solana')), common_input TEXT, resolved BIGINT NOT NULL DEFAULT 0 CHECK(resolved IN(0,1)));

CREATE TABLE source_recovery_approvals(obligation_id TEXT NOT NULL REFERENCES obligations(id), restoration_sequence BIGINT NOT NULL REFERENCES source_recoveries(critical_sequence), loss_sequence BIGINT NOT NULL REFERENCES source_recoveries(critical_sequence), prior_status TEXT NOT NULL CHECK(prior_status IN('ready','paying')), work_hash TEXT NOT NULL CHECK(length(work_hash)=64), reason TEXT NOT NULL CHECK(length(trim(reason))>0 AND length(reason)<=512), proof_json TEXT NOT NULL CHECK(bridge_json_valid(proof_json) AND length(proof_json)<=32768), critical_sequence BIGINT NOT NULL UNIQUE CHECK(critical_sequence>restoration_sequence), PRIMARY KEY(obligation_id,restoration_sequence));

CREATE TABLE source_loss_covers(critical_sequence BIGINT PRIMARY KEY, deposit_id TEXT NOT NULL REFERENCES deposits(id), recovery_sequence BIGINT NOT NULL UNIQUE REFERENCES source_recoveries(critical_sequence), amount BIGINT NOT NULL CHECK(amount>0), float_amount BIGINT NOT NULL CHECK(float_amount>=0 AND float_amount<=amount), earned_amount BIGINT NOT NULL CHECK(earned_amount=amount-float_amount), reason TEXT NOT NULL CHECK(length(trim(reason))>0 AND length(reason)<=512), proof_json TEXT NOT NULL CHECK(bridge_json_valid(proof_json) AND length(proof_json)<=32768), CHECK(critical_sequence>recovery_sequence));

CREATE TABLE attempts(txid TEXT PRIMARY KEY, intent_id TEXT NOT NULL REFERENCES intents(id), signed_bytes TEXT NOT NULL, policy_json TEXT NOT NULL, fee_limit BIGINT NOT NULL CHECK(fee_limit>=0), state TEXT NOT NULL CHECK(state IN('signed','broadcast_intent','settled','failed','review')), critical_sequence BIGINT, observation_json TEXT, preparation_generation BIGINT NOT NULL DEFAULT 0 CHECK(preparation_generation>=0));

CREATE TABLE fee_reservations(intent_id TEXT PRIMARY KEY REFERENCES intents(id), asset TEXT NOT NULL, amount BIGINT NOT NULL CHECK(amount>=0), released BIGINT NOT NULL DEFAULT 0 CHECK(released IN(0,1)));

CREATE TABLE source_loss_returns(cover_sequence BIGINT PRIMARY KEY REFERENCES source_loss_covers(critical_sequence), recovery_sequence BIGINT NOT NULL REFERENCES source_recoveries(critical_sequence), CHECK(recovery_sequence>cover_sequence));

CREATE TABLE solana_expiries(txid TEXT PRIMARY KEY REFERENCES attempts(txid), proof_json TEXT NOT NULL, critical_sequence BIGINT NOT NULL);

CREATE TABLE native_payment_recoveries(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, txid TEXT NOT NULL REFERENCES attempts(txid), previous_observation TEXT NOT NULL CHECK(bridge_json_valid(previous_observation) AND length(previous_observation)<=32768), state TEXT NOT NULL CHECK(state IN('confirming','unavailable','reconfirmed')), observation_json TEXT NOT NULL CHECK(bridge_json_valid(observation_json) AND length(observation_json)<=32768), critical_sequence BIGINT NOT NULL UNIQUE CHECK(critical_sequence>0));

CREATE TABLE native_replacement_drafts(critical_sequence BIGINT PRIMARY KEY CHECK(critical_sequence>0), parent_txid TEXT NOT NULL REFERENCES attempts(txid), fee BIGINT NOT NULL CHECK(fee>0), draft_json TEXT NOT NULL CHECK(bridge_json_valid(draft_json) AND length(draft_json)<=200000), work_hash TEXT NOT NULL CHECK(length(work_hash)=64), reason TEXT NOT NULL CHECK(length(trim(reason))>0 AND length(reason)<=512), proof_json TEXT NOT NULL CHECK(bridge_json_valid(proof_json) AND length(proof_json)<=32768), UNIQUE(parent_txid,fee,reason));

CREATE TABLE native_winner_changes(critical_sequence BIGINT PRIMARY KEY CHECK(critical_sequence>0), previous_txid TEXT NOT NULL REFERENCES attempts(txid), winner_txid TEXT NOT NULL REFERENCES attempts(txid), previous_observation TEXT NOT NULL CHECK(bridge_json_valid(previous_observation) AND length(previous_observation)<=32768), observation_json TEXT NOT NULL CHECK(bridge_json_valid(observation_json) AND length(observation_json)<=32768), evidence_hash TEXT NOT NULL REFERENCES observation_evidence(hash), fee_delta BIGINT NOT NULL CHECK(fee_delta<>0), CHECK(previous_txid<>winner_txid));

CREATE TABLE preparations(intent_id TEXT NOT NULL REFERENCES intents(id), generation BIGINT NOT NULL CHECK(generation>=0), policy_json TEXT NOT NULL, draft_json TEXT, retired_txid TEXT UNIQUE REFERENCES solana_expiries(txid), cancelled BIGINT NOT NULL DEFAULT 0 CHECK(cancelled IN(0,1)), PRIMARY KEY(intent_id,generation));

CREATE TABLE solana_retry_approvals(expired_txid TEXT PRIMARY KEY REFERENCES solana_expiries(txid), reason TEXT NOT NULL, proof_json TEXT NOT NULL, critical_sequence BIGINT NOT NULL);

CREATE TABLE native_replacement_cancellations(draft_sequence BIGINT PRIMARY KEY REFERENCES native_replacement_drafts(critical_sequence), reason TEXT NOT NULL CHECK(length(trim(reason))>0 AND length(reason)<=512), critical_sequence BIGINT NOT NULL UNIQUE CHECK(critical_sequence>draft_sequence));

CREATE TABLE native_replacement_members(draft_sequence BIGINT PRIMARY KEY REFERENCES native_replacement_drafts(critical_sequence), txid TEXT NOT NULL UNIQUE REFERENCES attempts(txid), critical_sequence BIGINT NOT NULL UNIQUE CHECK(critical_sequence>draft_sequence));

CREATE TABLE preparation_cancellations(intent_id TEXT NOT NULL, generation BIGINT NOT NULL, reason TEXT NOT NULL, cleanup_json TEXT NOT NULL, critical_sequence BIGINT NOT NULL CHECK(critical_sequence>0), completed BIGINT NOT NULL DEFAULT 0 CHECK(completed IN(0,1)), PRIMARY KEY(intent_id,generation), FOREIGN KEY(intent_id,generation) REFERENCES preparations(intent_id,generation));

CREATE INDEX posting_balance ON postings(asset,account);

CREATE UNIQUE INDEX one_conversion ON obligations(order_id) WHERE kind='conversion';

CREATE UNIQUE INDEX one_unresolved_chain_intent ON intents(chain) WHERE resolved=0;

CREATE UNIQUE INDEX one_active_deposit_allocation ON obligations(deposit_id) WHERE status<>'cancelled';

CREATE INDEX chain_event_review ON chain_events(chain,needs_review,kind);

CREATE INDEX operating_cost_time ON operating_costs(recorded_at);

CREATE UNIQUE INDEX one_active_preparation ON preparations(intent_id) WHERE retired_txid IS NULL AND cancelled=0;

CREATE INDEX native_payment_recovery_latest ON native_payment_recoveries(txid,id);

CREATE INDEX source_recovery_latest ON source_recoveries(deposit_id,id);

CREATE VIEW source_recovery_state AS SELECT r.* FROM source_recoveries r WHERE r.id=(SELECT MAX(p.id) FROM source_recoveries p WHERE p.deposit_id=r.deposit_id);

CREATE INDEX source_loss_deposit ON source_loss_covers(deposit_id);

CREATE VIEW active_source_loss_covers AS SELECT f.* FROM source_loss_covers f WHERE NOT EXISTS(SELECT 1 FROM source_loss_returns r WHERE r.cover_sequence=f.critical_sequence);

CREATE VIEW proven_source_losses AS SELECT d.id AS deposit_id FROM deposits d JOIN source_recovery_state r ON r.deposit_id=d.id WHERE d.asset='Native' AND d.eligible=0 AND r.state='missing' AND r.shortfall=d.amount;

CREATE VIEW accounted_source_losses AS SELECT f.deposit_id FROM active_source_loss_covers f JOIN source_recovery_state r ON r.deposit_id=f.deposit_id JOIN deposits d ON d.id=f.deposit_id WHERE d.asset='Native' AND d.eligible=0 AND r.state='missing' AND r.shortfall=d.amount AND f.amount=d.amount;

CREATE UNIQUE INDEX one_settled_payment_per_intent ON attempts(intent_id) WHERE state='settled';

CREATE INDEX native_winner_change_history ON native_winner_changes(winner_txid,critical_sequence);

CREATE VIEW native_payment_recovery_state AS SELECT r.* FROM native_payment_recoveries r JOIN attempts a ON a.txid=r.txid WHERE a.state='settled' AND r.id=(SELECT MAX(p.id) FROM native_payment_recoveries p WHERE p.txid=r.txid) AND r.critical_sequence>COALESCE((SELECT MAX(w.critical_sequence) FROM native_winner_changes w WHERE w.winner_txid=r.txid),0);

CREATE FUNCTION trg_immutable_order() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.id IS DISTINCT FROM OLD.id OR NEW.capability_hash IS DISTINCT FROM OLD.capability_hash OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key OR NEW.request_hash IS DISTINCT FROM OLD.request_hash OR NEW.request_json IS DISTINCT FROM OLD.request_json OR NEW.quote_json IS DISTINCT FROM OLD.quote_json OR NEW.policy_json IS DISTINCT FROM OLD.policy_json OR NEW.deadline IS DISTINCT FROM OLD.deadline OR NEW.grace_deadline IS DISTINCT FROM OLD.grace_deadline) THEN RAISE EXCEPTION 'immutable_order' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_order BEFORE UPDATE OF id,capability_hash,idempotency_key,request_hash,request_json,quote_json,policy_json,deadline,grace_deadline ON orders FOR EACH ROW EXECUTE FUNCTION trg_immutable_order();

CREATE FUNCTION trg_immutable_posting_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'append_only_journal' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_posting_update BEFORE UPDATE ON postings FOR EACH ROW EXECUTE FUNCTION trg_immutable_posting_update();

CREATE FUNCTION trg_immutable_posting_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'append_only_journal' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_posting_delete BEFORE DELETE ON postings FOR EACH ROW EXECUTE FUNCTION trg_immutable_posting_delete();

CREATE FUNCTION trg_immutable_signed_bytes() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.txid IS DISTINCT FROM OLD.txid OR NEW.intent_id IS DISTINCT FROM OLD.intent_id OR NEW.signed_bytes IS DISTINCT FROM OLD.signed_bytes OR NEW.policy_json IS DISTINCT FROM OLD.policy_json OR NEW.fee_limit IS DISTINCT FROM OLD.fee_limit) THEN RAISE EXCEPTION 'immutable_attempt' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_signed_bytes BEFORE UPDATE OF txid,intent_id,signed_bytes,policy_json,fee_limit ON attempts FOR EACH ROW EXECUTE FUNCTION trg_immutable_signed_bytes();

CREATE FUNCTION trg_immutable_evidence_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_evidence' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_evidence_update BEFORE UPDATE ON observation_evidence FOR EACH ROW EXECUTE FUNCTION trg_immutable_evidence_update();

CREATE FUNCTION trg_immutable_evidence_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_evidence' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_evidence_delete BEFORE DELETE ON observation_evidence FOR EACH ROW EXECUTE FUNCTION trg_immutable_evidence_delete();

CREATE FUNCTION trg_immutable_scan_origin() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_scan_origin' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_scan_origin BEFORE UPDATE ON scan_origins FOR EACH ROW EXECUTE FUNCTION trg_immutable_scan_origin();

CREATE FUNCTION trg_immutable_treasury_allocation_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_treasury_allocation' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_treasury_allocation_update BEFORE UPDATE ON treasury_allocations FOR EACH ROW EXECUTE FUNCTION trg_immutable_treasury_allocation_update();

CREATE FUNCTION trg_immutable_treasury_allocation_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_treasury_allocation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_treasury_allocation_delete BEFORE DELETE ON treasury_allocations FOR EACH ROW EXECUTE FUNCTION trg_immutable_treasury_allocation_delete();

CREATE FUNCTION trg_immutable_treasury_spend_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_treasury_spend' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_treasury_spend_update BEFORE UPDATE ON treasury_spends FOR EACH ROW EXECUTE FUNCTION trg_immutable_treasury_spend_update();

CREATE FUNCTION trg_immutable_treasury_spend_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_treasury_spend' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_treasury_spend_delete BEFORE DELETE ON treasury_spends FOR EACH ROW EXECUTE FUNCTION trg_immutable_treasury_spend_delete();

CREATE FUNCTION trg_immutable_solana_expiry_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_solana_expiry' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_solana_expiry_update BEFORE UPDATE ON solana_expiries FOR EACH ROW EXECUTE FUNCTION trg_immutable_solana_expiry_update();

CREATE FUNCTION trg_immutable_solana_expiry_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_solana_expiry' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_solana_expiry_delete BEFORE DELETE ON solana_expiries FOR EACH ROW EXECUTE FUNCTION trg_immutable_solana_expiry_delete();

CREATE FUNCTION trg_immutable_preparation_policy() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.intent_id IS DISTINCT FROM OLD.intent_id OR NEW.generation IS DISTINCT FROM OLD.generation OR NEW.policy_json IS DISTINCT FROM OLD.policy_json) THEN RAISE EXCEPTION 'immutable_preparation' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_preparation_policy BEFORE UPDATE OF intent_id,generation,policy_json ON preparations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_policy();

CREATE FUNCTION trg_immutable_preparation_draft() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.draft_json IS DISTINCT FROM OLD.draft_json) AND (OLD.draft_json IS NOT NULL) THEN RAISE EXCEPTION 'immutable_preparation_draft' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_preparation_draft BEFORE UPDATE OF draft_json ON preparations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_draft();

CREATE FUNCTION trg_immutable_preparation_retirement() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.retired_txid IS DISTINCT FROM OLD.retired_txid) AND (OLD.retired_txid IS NOT NULL) THEN RAISE EXCEPTION 'immutable_preparation_retirement' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_preparation_retirement BEFORE UPDATE OF retired_txid ON preparations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_retirement();

CREATE FUNCTION trg_immutable_preparation_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_preparation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_preparation_delete BEFORE DELETE ON preparations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_delete();

CREATE FUNCTION trg_immutable_attempt_generation() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.preparation_generation IS DISTINCT FROM OLD.preparation_generation) THEN RAISE EXCEPTION 'immutable_attempt' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_attempt_generation BEFORE UPDATE OF preparation_generation ON attempts FOR EACH ROW EXECUTE FUNCTION trg_immutable_attempt_generation();

CREATE FUNCTION trg_immutable_retry_approval_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_retry_approval' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_retry_approval_update BEFORE UPDATE ON solana_retry_approvals FOR EACH ROW EXECUTE FUNCTION trg_immutable_retry_approval_update();

CREATE FUNCTION trg_immutable_retry_approval_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_retry_approval' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_retry_approval_delete BEFORE DELETE ON solana_retry_approvals FOR EACH ROW EXECUTE FUNCTION trg_immutable_retry_approval_delete();

CREATE FUNCTION trg_immutable_operating_cost_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_operating_cost' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_operating_cost_update BEFORE UPDATE ON operating_costs FOR EACH ROW EXECUTE FUNCTION trg_immutable_operating_cost_update();

CREATE FUNCTION trg_immutable_operating_cost_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_operating_cost' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_operating_cost_delete BEFORE DELETE ON operating_costs FOR EACH ROW EXECUTE FUNCTION trg_immutable_operating_cost_delete();

CREATE FUNCTION trg_record_operating_cost() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NEW.account='operating' AND NEW.delta<0 THEN UPDATE operating_clock SET last_time=GREATEST(last_time,floor(extract(epoch FROM clock_timestamp()))::bigint); INSERT INTO operating_costs(posting_id,recorded_at) SELECT NEW.id,last_time FROM operating_clock; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER record_operating_cost AFTER INSERT ON postings FOR EACH ROW EXECUTE FUNCTION trg_record_operating_cost();

CREATE FUNCTION trg_immutable_order_cost_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_order_cost_limits' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_order_cost_update BEFORE UPDATE ON order_cost_limits FOR EACH ROW EXECUTE FUNCTION trg_immutable_order_cost_update();

CREATE FUNCTION trg_immutable_order_cost_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_order_cost_limits' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_order_cost_delete BEFORE DELETE ON order_cost_limits FOR EACH ROW EXECUTE FUNCTION trg_immutable_order_cost_delete();

CREATE FUNCTION trg_immutable_operating_reservation() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.order_id IS DISTINCT FROM OLD.order_id OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.asset IS DISTINCT FROM OLD.asset OR NEW.amount IS DISTINCT FROM OLD.amount) THEN RAISE EXCEPTION 'immutable_operating_reservation' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_operating_reservation BEFORE UPDATE OF order_id,kind,asset,amount ON operating_reservations FOR EACH ROW EXECUTE FUNCTION trg_immutable_operating_reservation();

CREATE FUNCTION trg_immutable_operating_reservation_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_operating_reservation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_operating_reservation_delete BEFORE DELETE ON operating_reservations FOR EACH ROW EXECUTE FUNCTION trg_immutable_operating_reservation_delete();

CREATE FUNCTION trg_immutable_instruction() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.instruction IS DISTINCT FROM OLD.instruction OR NEW.instruction_sequence IS DISTINCT FROM OLD.instruction_sequence) AND (OLD.instruction IS NOT NULL AND (NEW.instruction IS DISTINCT FROM OLD.instruction OR NEW.instruction_sequence IS DISTINCT FROM OLD.instruction_sequence)) THEN RAISE EXCEPTION 'immutable_instruction' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_instruction BEFORE UPDATE OF instruction,instruction_sequence ON orders FOR EACH ROW EXECUTE FUNCTION trg_immutable_instruction();

CREATE FUNCTION trg_irreversible_instruction_issue() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.instruction_issued IS DISTINCT FROM OLD.instruction_issued) AND (NEW.instruction_issued<OLD.instruction_issued OR (NEW.instruction_issued=1 AND NEW.instruction IS NULL)) THEN RAISE EXCEPTION 'invalid_instruction_issue' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER irreversible_instruction_issue BEFORE UPDATE OF instruction_issued ON orders FOR EACH ROW EXECUTE FUNCTION trg_irreversible_instruction_issue();

CREATE FUNCTION trg_immutable_native_allocation_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_allocation' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_allocation_update BEFORE UPDATE ON native_allocations FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_allocation_update();

CREATE FUNCTION trg_immutable_native_allocation_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_allocation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_allocation_delete BEFORE DELETE ON native_allocations FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_allocation_delete();

CREATE FUNCTION trg_custody_posting() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_posting AFTER INSERT ON postings FOR EACH ROW EXECUTE FUNCTION trg_custody_posting();

CREATE FUNCTION trg_custody_deposit_insert() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_deposit_insert AFTER INSERT ON deposits FOR EACH ROW EXECUTE FUNCTION trg_custody_deposit_insert();

CREATE FUNCTION trg_custody_deposit_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_deposit_update AFTER UPDATE ON deposits FOR EACH ROW EXECUTE FUNCTION trg_custody_deposit_update();

CREATE FUNCTION trg_custody_attempt_insert() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_attempt_insert AFTER INSERT ON attempts FOR EACH ROW EXECUTE FUNCTION trg_custody_attempt_insert();

CREATE FUNCTION trg_custody_attempt_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_attempt_update AFTER UPDATE ON attempts FOR EACH ROW EXECUTE FUNCTION trg_custody_attempt_update();

CREATE FUNCTION trg_custody_checkpoint_insert() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_checkpoint_insert AFTER INSERT ON checkpoints FOR EACH ROW EXECUTE FUNCTION trg_custody_checkpoint_insert();

CREATE FUNCTION trg_custody_checkpoint_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_checkpoint_update AFTER UPDATE ON checkpoints FOR EACH ROW EXECUTE FUNCTION trg_custody_checkpoint_update();

CREATE FUNCTION trg_custody_scan_insert() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_scan_insert AFTER INSERT ON scan_health FOR EACH ROW EXECUTE FUNCTION trg_custody_scan_insert();

CREATE FUNCTION trg_custody_scan_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_scan_update AFTER UPDATE ON scan_health FOR EACH ROW EXECUTE FUNCTION trg_custody_scan_update();

CREATE FUNCTION trg_custody_event_insert() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_event_insert AFTER INSERT ON chain_events FOR EACH ROW EXECUTE FUNCTION trg_custody_event_insert();

CREATE FUNCTION trg_custody_event_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_event_update AFTER UPDATE ON chain_events FOR EACH ROW EXECUTE FUNCTION trg_custody_event_update();

CREATE FUNCTION trg_immutable_preparation_cancellation() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.intent_id IS DISTINCT FROM OLD.intent_id OR NEW.generation IS DISTINCT FROM OLD.generation OR NEW.reason IS DISTINCT FROM OLD.reason OR NEW.cleanup_json IS DISTINCT FROM OLD.cleanup_json OR NEW.critical_sequence IS DISTINCT FROM OLD.critical_sequence) THEN RAISE EXCEPTION 'immutable_preparation_cancellation' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_preparation_cancellation BEFORE UPDATE OF intent_id,generation,reason,cleanup_json,critical_sequence ON preparation_cancellations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_cancellation();

CREATE FUNCTION trg_immutable_preparation_cancellation_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_preparation_cancellation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_preparation_cancellation_delete BEFORE DELETE ON preparation_cancellations FOR EACH ROW EXECUTE FUNCTION trg_immutable_preparation_cancellation_delete();

CREATE FUNCTION trg_irreversible_preparation_cleanup() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.completed IS DISTINCT FROM OLD.completed) AND (NEW.completed<OLD.completed) THEN RAISE EXCEPTION 'irreversible_preparation_cleanup' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER irreversible_preparation_cleanup BEFORE UPDATE OF completed ON preparation_cancellations FOR EACH ROW EXECUTE FUNCTION trg_irreversible_preparation_cleanup();

CREATE FUNCTION trg_irreversible_preparation_cancellation() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.cancelled IS DISTINCT FROM OLD.cancelled) AND (NEW.cancelled<OLD.cancelled OR (NEW.cancelled=1 AND (NEW.retired_txid IS NOT NULL OR NOT EXISTS(SELECT 1 FROM preparation_cancellations c WHERE c.intent_id=NEW.intent_id AND c.generation=NEW.generation AND c.completed=1) OR EXISTS(SELECT 1 FROM attempts a WHERE a.intent_id=NEW.intent_id AND a.preparation_generation=NEW.generation)))) THEN RAISE EXCEPTION 'invalid_preparation_cancellation' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER irreversible_preparation_cancellation BEFORE UPDATE OF cancelled ON preparations FOR EACH ROW EXECUTE FUNCTION trg_irreversible_preparation_cancellation();

CREATE FUNCTION trg_cancelled_preparation_draft() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF (NEW.draft_json IS DISTINCT FROM OLD.draft_json) AND (EXISTS(SELECT 1 FROM preparation_cancellations c WHERE c.intent_id=NEW.intent_id AND c.generation=NEW.generation)) THEN RAISE EXCEPTION 'preparation_cancellation_pending' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER cancelled_preparation_draft BEFORE UPDATE OF draft_json ON preparations FOR EACH ROW EXECUTE FUNCTION trg_cancelled_preparation_draft();

CREATE FUNCTION trg_cancelled_preparation_attempt() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM preparations p JOIN intents i ON i.id=p.intent_id WHERE p.intent_id=NEW.intent_id AND p.generation=NEW.preparation_generation AND i.resolved=0 AND p.retired_txid IS NULL AND p.cancelled=0) OR EXISTS(SELECT 1 FROM preparation_cancellations c WHERE c.intent_id=NEW.intent_id AND c.generation=NEW.preparation_generation) THEN RAISE EXCEPTION 'preparation_not_active' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER cancelled_preparation_attempt BEFORE INSERT ON attempts FOR EACH ROW EXECUTE FUNCTION trg_cancelled_preparation_attempt();

CREATE FUNCTION trg_immutable_native_payment_recovery_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_payment_recovery' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_payment_recovery_update BEFORE UPDATE ON native_payment_recoveries FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_payment_recovery_update();

CREATE FUNCTION trg_immutable_native_payment_recovery_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_payment_recovery' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_payment_recovery_delete BEFORE DELETE ON native_payment_recoveries FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_payment_recovery_delete();

CREATE FUNCTION trg_native_payment_recovery_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM attempts a JOIN intents i ON i.id=a.intent_id WHERE a.txid=NEW.txid AND a.state='settled' AND i.chain='Native' AND a.observation_json=NEW.previous_observation) THEN RAISE EXCEPTION 'native_payment_recovery_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER native_payment_recovery_binding BEFORE INSERT ON native_payment_recoveries FOR EACH ROW EXECUTE FUNCTION trg_native_payment_recovery_binding();

CREATE FUNCTION trg_custody_native_payment_recovery() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_native_payment_recovery AFTER INSERT ON native_payment_recoveries FOR EACH ROW EXECUTE FUNCTION trg_custody_native_payment_recovery();

CREATE FUNCTION trg_immutable_source_recovery_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_recovery' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_source_recovery_update BEFORE UPDATE ON source_recoveries FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_recovery_update();

CREATE FUNCTION trg_immutable_source_recovery_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_recovery' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_source_recovery_delete BEFORE DELETE ON source_recoveries FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_recovery_delete();

CREATE FUNCTION trg_source_recovery_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM deposits d WHERE d.id=NEW.deposit_id AND NEW.shortfall IN(0,d.amount) AND (NEW.shortfall=0 OR d.asset='Native') AND (NEW.state<>'missing' OR NEW.shortfall=d.amount AND d.eligible=0) AND (NEW.state<>'restored' OR NEW.shortfall=0 AND d.eligible=1)) THEN RAISE EXCEPTION 'source_recovery_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER source_recovery_binding BEFORE INSERT ON source_recoveries FOR EACH ROW EXECUTE FUNCTION trg_source_recovery_binding();

CREATE FUNCTION trg_custody_source_recovery() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_source_recovery AFTER INSERT ON source_recoveries FOR EACH ROW EXECUTE FUNCTION trg_custody_source_recovery();

CREATE FUNCTION trg_immutable_source_approval_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_approval' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_source_approval_update BEFORE UPDATE ON source_recovery_approvals FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_approval_update();

CREATE FUNCTION trg_immutable_source_approval_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_approval' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_source_approval_delete BEFORE DELETE ON source_recovery_approvals FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_approval_delete();

CREATE FUNCTION trg_source_approval_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM obligations o JOIN deposits d ON d.id=o.deposit_id JOIN source_recovery_state r ON r.deposit_id=d.id JOIN source_recoveries loss ON loss.critical_sequence=NEW.loss_sequence WHERE o.id=NEW.obligation_id AND o.status='review' AND d.eligible=1 AND r.state='restored' AND r.shortfall=0 AND r.critical_sequence=NEW.restoration_sequence AND loss.deposit_id=d.id AND loss.critical_sequence<r.critical_sequence) THEN RAISE EXCEPTION 'source_approval_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER source_approval_binding BEFORE INSERT ON source_recovery_approvals FOR EACH ROW EXECUTE FUNCTION trg_source_approval_binding();

CREATE FUNCTION trg_custody_source_approval() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_source_approval AFTER INSERT ON source_recovery_approvals FOR EACH ROW EXECUTE FUNCTION trg_custody_source_approval();

CREATE FUNCTION trg_source_loss_cover_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF EXISTS(SELECT 1 FROM active_source_loss_covers f WHERE f.deposit_id=NEW.deposit_id) OR NOT EXISTS(SELECT 1 FROM deposits d JOIN source_recovery_state r ON r.deposit_id=d.id WHERE d.id=NEW.deposit_id AND d.asset='Native' AND d.eligible=0 AND r.state='missing' AND r.shortfall=d.amount AND NEW.amount=d.amount AND r.critical_sequence=NEW.recovery_sequence) THEN RAISE EXCEPTION 'source_loss_cover_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER source_loss_cover_binding BEFORE INSERT ON source_loss_covers FOR EACH ROW EXECUTE FUNCTION trg_source_loss_cover_binding();

CREATE FUNCTION trg_source_loss_return_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM active_source_loss_covers f JOIN source_recovery_state r ON r.deposit_id=f.deposit_id WHERE f.critical_sequence=NEW.cover_sequence AND r.critical_sequence=NEW.recovery_sequence AND r.state IN('pending','restored') AND r.shortfall=0) THEN RAISE EXCEPTION 'source_loss_return_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER source_loss_return_binding BEFORE INSERT ON source_loss_returns FOR EACH ROW EXECUTE FUNCTION trg_source_loss_return_binding();

CREATE FUNCTION trg_immutable_source_cover_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_loss_cover' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_source_cover_update BEFORE UPDATE ON source_loss_covers FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_cover_update();

CREATE FUNCTION trg_immutable_source_cover_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_loss_cover' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_source_cover_delete BEFORE DELETE ON source_loss_covers FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_cover_delete();

CREATE FUNCTION trg_immutable_source_return_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_loss_return' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_source_return_update BEFORE UPDATE ON source_loss_returns FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_return_update();

CREATE FUNCTION trg_immutable_source_return_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_source_loss_return' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_source_return_delete BEFORE DELETE ON source_loss_returns FOR EACH ROW EXECUTE FUNCTION trg_immutable_source_return_delete();

CREATE FUNCTION trg_custody_source_cover() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_source_cover AFTER INSERT ON source_loss_covers FOR EACH ROW EXECUTE FUNCTION trg_custody_source_cover();

CREATE FUNCTION trg_custody_source_return() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_source_return AFTER INSERT ON source_loss_returns FOR EACH ROW EXECUTE FUNCTION trg_custody_source_return();

CREATE FUNCTION trg_immutable_native_replacement_draft_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_draft' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_replacement_draft_update BEFORE UPDATE ON native_replacement_drafts FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_draft_update();

CREATE FUNCTION trg_immutable_native_replacement_draft_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_draft' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_replacement_draft_delete BEFORE DELETE ON native_replacement_drafts FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_draft_delete();

CREATE FUNCTION trg_immutable_native_replacement_cancel_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_cancellation' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_replacement_cancel_update BEFORE UPDATE ON native_replacement_cancellations FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_cancel_update();

CREATE FUNCTION trg_immutable_native_replacement_cancel_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_cancellation' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_replacement_cancel_delete BEFORE DELETE ON native_replacement_cancellations FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_cancel_delete();

CREATE FUNCTION trg_custody_native_replacement_draft() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_native_replacement_draft AFTER INSERT ON native_replacement_drafts FOR EACH ROW EXECUTE FUNCTION trg_custody_native_replacement_draft();

CREATE FUNCTION trg_custody_native_replacement_cancel() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_native_replacement_cancel AFTER INSERT ON native_replacement_cancellations FOR EACH ROW EXECUTE FUNCTION trg_custody_native_replacement_cancel();

CREATE FUNCTION trg_native_replacement_member_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM native_replacement_drafts d JOIN attempts parent ON parent.txid=d.parent_txid JOIN attempts child ON child.txid=NEW.txid JOIN intents i ON i.id=parent.intent_id WHERE parent.intent_id=child.intent_id AND parent.preparation_generation=child.preparation_generation AND parent.state='broadcast_intent' AND child.state='signed' AND child.fee_limit=parent.fee_limit AND child.txid<>parent.txid AND i.chain='Native' AND i.resolved=0 AND d.critical_sequence=NEW.draft_sequence AND NOT EXISTS(SELECT 1 FROM native_replacement_cancellations x WHERE x.draft_sequence=d.critical_sequence)) THEN RAISE EXCEPTION 'native_replacement_member_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER native_replacement_member_binding BEFORE INSERT ON native_replacement_members FOR EACH ROW EXECUTE FUNCTION trg_native_replacement_member_binding();

CREATE FUNCTION trg_immutable_native_replacement_member_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_member' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_replacement_member_update BEFORE UPDATE ON native_replacement_members FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_member_update();

CREATE FUNCTION trg_immutable_native_replacement_member_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_replacement_member' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_replacement_member_delete BEFORE DELETE ON native_replacement_members FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_replacement_member_delete();

CREATE FUNCTION trg_native_replacement_cancel_unsigned() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF EXISTS(SELECT 1 FROM native_replacement_members m WHERE m.draft_sequence=NEW.draft_sequence) THEN RAISE EXCEPTION 'native_replacement_already_signed' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER native_replacement_cancel_unsigned BEFORE INSERT ON native_replacement_cancellations FOR EACH ROW EXECUTE FUNCTION trg_native_replacement_cancel_unsigned();

CREATE FUNCTION trg_native_replacement_draft_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM attempts a JOIN intents i ON i.id=a.intent_id JOIN obligations o ON o.id=i.obligation_id JOIN deposits d ON d.id=o.deposit_id JOIN fee_reservations f ON f.intent_id=i.id WHERE a.txid=NEW.parent_txid AND a.state='broadcast_intent' AND i.chain='Native' AND i.resolved=0 AND o.status='paying' AND d.eligible=1 AND f.asset='Native' AND f.released=0 AND f.amount>=a.fee_limit AND NEW.fee<=a.fee_limit) OR EXISTS(SELECT 1 FROM native_replacement_drafts r JOIN attempts a ON a.txid=r.parent_txid WHERE a.intent_id=(SELECT intent_id FROM attempts WHERE txid=NEW.parent_txid) AND NOT EXISTS(SELECT 1 FROM native_replacement_cancellations x WHERE x.draft_sequence=r.critical_sequence) AND NOT EXISTS(SELECT 1 FROM native_replacement_members m WHERE m.draft_sequence=r.critical_sequence)) THEN RAISE EXCEPTION 'native_replacement_draft_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER native_replacement_draft_binding BEFORE INSERT ON native_replacement_drafts FOR EACH ROW EXECUTE FUNCTION trg_native_replacement_draft_binding();

CREATE FUNCTION trg_custody_native_replacement_member() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_native_replacement_member AFTER INSERT ON native_replacement_members FOR EACH ROW EXECUTE FUNCTION trg_custody_native_replacement_member();

CREATE FUNCTION trg_native_winner_change_binding() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN IF NOT EXISTS(SELECT 1 FROM attempts prior JOIN attempts winner ON winner.intent_id=prior.intent_id JOIN intents i ON i.id=prior.intent_id WHERE prior.txid=NEW.previous_txid AND winner.txid=NEW.winner_txid AND prior.state='settled' AND prior.observation_json=NEW.previous_observation AND winner.state IN('broadcast_intent','review') AND prior.critical_sequence>0 AND winner.critical_sequence>0 AND prior.preparation_generation=winner.preparation_generation AND prior.fee_limit=winner.fee_limit AND i.chain='Native' AND i.resolved=1) THEN RAISE EXCEPTION 'native_winner_change_binding' USING ERRCODE='23514'; END IF; RETURN NEW; END
$body$;
CREATE TRIGGER native_winner_change_binding BEFORE INSERT ON native_winner_changes FOR EACH ROW EXECUTE FUNCTION trg_native_winner_change_binding();

CREATE FUNCTION trg_immutable_native_winner_change_update() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_winner_change' USING ERRCODE='23514'; RETURN NEW; END
$body$;
CREATE TRIGGER immutable_native_winner_change_update BEFORE UPDATE ON native_winner_changes FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_winner_change_update();

CREATE FUNCTION trg_immutable_native_winner_change_delete() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN RAISE EXCEPTION 'immutable_native_winner_change' USING ERRCODE='23514'; RETURN OLD; END
$body$;
CREATE TRIGGER immutable_native_winner_change_delete BEFORE DELETE ON native_winner_changes FOR EACH ROW EXECUTE FUNCTION trg_immutable_native_winner_change_delete();

CREATE FUNCTION trg_custody_native_winner_change() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN UPDATE custody_check SET revision=revision+1; RETURN NEW; END
$body$;
CREATE TRIGGER custody_native_winner_change AFTER INSERT ON native_winner_changes FOR EACH ROW EXECUTE FUNCTION trg_custody_native_winner_change();

COMMIT;
